/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.AlembicVersion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlembicVersionRecord extends UpdatableRecordImpl<AlembicVersionRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.alembic_version.version_num</code>.
     */
    public void setVersionNum(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alembic_version.version_num</code>.
     */
    public String getVersionNum() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AlembicVersion.ALEMBIC_VERSION.VERSION_NUM;
    }

    @Override
    public String component1() {
        return getVersionNum();
    }

    @Override
    public String value1() {
        return getVersionNum();
    }

    @Override
    public AlembicVersionRecord value1(String value) {
        setVersionNum(value);
        return this;
    }

    @Override
    public AlembicVersionRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlembicVersionRecord
     */
    public AlembicVersionRecord() {
        super(AlembicVersion.ALEMBIC_VERSION);
    }

    /**
     * Create a detached, initialised AlembicVersionRecord
     */
    public AlembicVersionRecord(String versionNum) {
        super(AlembicVersion.ALEMBIC_VERSION);

        setVersionNum(versionNum);
    }
}
