/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.ApiRequests;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiRequestsRecord extends UpdatableRecordImpl<ApiRequestsRecord> implements Record8<UUID, UUID, UUID, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.api_requests.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.api_requests.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.api_requests.tenant_id</code>.
     */
    public void setTenantId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.api_requests.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.api_requests.api_token_id</code>.
     */
    public void setApiTokenId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.api_requests.api_token_id</code>.
     */
    public UUID getApiTokenId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.api_requests.path</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.api_requests.path</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.api_requests.request</code>.
     */
    public void setRequest(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.api_requests.request</code>.
     */
    public String getRequest() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.api_requests.response</code>.
     */
    public void setResponse(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.api_requests.response</code>.
     */
    public String getResponse() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.api_requests.ip</code>.
     */
    public void setIp(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.api_requests.ip</code>.
     */
    public String getIp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.api_requests.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.api_requests.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, UUID, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, UUID, UUID, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ApiRequests.API_REQUESTS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return ApiRequests.API_REQUESTS.TENANT_ID;
    }

    @Override
    public Field<UUID> field3() {
        return ApiRequests.API_REQUESTS.API_TOKEN_ID;
    }

    @Override
    public Field<String> field4() {
        return ApiRequests.API_REQUESTS.PATH;
    }

    @Override
    public Field<String> field5() {
        return ApiRequests.API_REQUESTS.REQUEST;
    }

    @Override
    public Field<String> field6() {
        return ApiRequests.API_REQUESTS.RESPONSE;
    }

    @Override
    public Field<String> field7() {
        return ApiRequests.API_REQUESTS.IP;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ApiRequests.API_REQUESTS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getTenantId();
    }

    @Override
    public UUID component3() {
        return getApiTokenId();
    }

    @Override
    public String component4() {
        return getPath();
    }

    @Override
    public String component5() {
        return getRequest();
    }

    @Override
    public String component6() {
        return getResponse();
    }

    @Override
    public String component7() {
        return getIp();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getTenantId();
    }

    @Override
    public UUID value3() {
        return getApiTokenId();
    }

    @Override
    public String value4() {
        return getPath();
    }

    @Override
    public String value5() {
        return getRequest();
    }

    @Override
    public String value6() {
        return getResponse();
    }

    @Override
    public String value7() {
        return getIp();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public ApiRequestsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value2(UUID value) {
        setTenantId(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value3(UUID value) {
        setApiTokenId(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value4(String value) {
        setPath(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value5(String value) {
        setRequest(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value6(String value) {
        setResponse(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value7(String value) {
        setIp(value);
        return this;
    }

    @Override
    public ApiRequestsRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ApiRequestsRecord values(UUID value1, UUID value2, UUID value3, String value4, String value5, String value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiRequestsRecord
     */
    public ApiRequestsRecord() {
        super(ApiRequests.API_REQUESTS);
    }

    /**
     * Create a detached, initialised ApiRequestsRecord
     */
    public ApiRequestsRecord(UUID id, UUID tenantId, UUID apiTokenId, String path, String request, String response, String ip, LocalDateTime createdAt) {
        super(ApiRequests.API_REQUESTS);

        setId(id);
        setTenantId(tenantId);
        setApiTokenId(apiTokenId);
        setPath(path);
        setRequest(request);
        setResponse(response);
        setIp(ip);
        setCreatedAt(createdAt);
    }
}
