/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.AppAnnotationHitHistories;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppAnnotationHitHistoriesRecord extends UpdatableRecordImpl<AppAnnotationHitHistoriesRecord> implements Record11<UUID, UUID, UUID, String, String, UUID, LocalDateTime, Double, UUID, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_annotation_hit_histories.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.app_id</code>.
     */
    public void setAppId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.app_id</code>.
     */
    public UUID getAppId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.annotation_id</code>.
     */
    public void setAnnotationId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.annotation_id</code>.
     */
    public UUID getAnnotationId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.source</code>.
     */
    public void setSource(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.source</code>.
     */
    public String getSource() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.question</code>.
     */
    public void setQuestion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.question</code>.
     */
    public String getQuestion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.score</code>.
     */
    public void setScore(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.score</code>.
     */
    public Double getScore() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.message_id</code>.
     */
    public void setMessageId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.message_id</code>.
     */
    public UUID getMessageId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.annotation_question</code>.
     */
    public void setAnnotationQuestion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.annotation_question</code>.
     */
    public String getAnnotationQuestion() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.app_annotation_hit_histories.annotation_content</code>.
     */
    public void setAnnotationContent(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.app_annotation_hit_histories.annotation_content</code>.
     */
    public String getAnnotationContent() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, UUID, UUID, String, String, UUID, LocalDateTime, Double, UUID, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, UUID, UUID, String, String, UUID, LocalDateTime, Double, UUID, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.APP_ID;
    }

    @Override
    public Field<UUID> field3() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_ID;
    }

    @Override
    public Field<String> field4() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SOURCE;
    }

    @Override
    public Field<String> field5() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.QUESTION;
    }

    @Override
    public Field<UUID> field6() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ACCOUNT_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.CREATED_AT;
    }

    @Override
    public Field<Double> field8() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SCORE;
    }

    @Override
    public Field<UUID> field9() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.MESSAGE_ID;
    }

    @Override
    public Field<String> field10() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_QUESTION;
    }

    @Override
    public Field<String> field11() {
        return AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_CONTENT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getAppId();
    }

    @Override
    public UUID component3() {
        return getAnnotationId();
    }

    @Override
    public String component4() {
        return getSource();
    }

    @Override
    public String component5() {
        return getQuestion();
    }

    @Override
    public UUID component6() {
        return getAccountId();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public Double component8() {
        return getScore();
    }

    @Override
    public UUID component9() {
        return getMessageId();
    }

    @Override
    public String component10() {
        return getAnnotationQuestion();
    }

    @Override
    public String component11() {
        return getAnnotationContent();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getAppId();
    }

    @Override
    public UUID value3() {
        return getAnnotationId();
    }

    @Override
    public String value4() {
        return getSource();
    }

    @Override
    public String value5() {
        return getQuestion();
    }

    @Override
    public UUID value6() {
        return getAccountId();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public Double value8() {
        return getScore();
    }

    @Override
    public UUID value9() {
        return getMessageId();
    }

    @Override
    public String value10() {
        return getAnnotationQuestion();
    }

    @Override
    public String value11() {
        return getAnnotationContent();
    }

    @Override
    public AppAnnotationHitHistoriesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value2(UUID value) {
        setAppId(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value3(UUID value) {
        setAnnotationId(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value4(String value) {
        setSource(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value5(String value) {
        setQuestion(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value6(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value8(Double value) {
        setScore(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value9(UUID value) {
        setMessageId(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value10(String value) {
        setAnnotationQuestion(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord value11(String value) {
        setAnnotationContent(value);
        return this;
    }

    @Override
    public AppAnnotationHitHistoriesRecord values(UUID value1, UUID value2, UUID value3, String value4, String value5, UUID value6, LocalDateTime value7, Double value8, UUID value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppAnnotationHitHistoriesRecord
     */
    public AppAnnotationHitHistoriesRecord() {
        super(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES);
    }

    /**
     * Create a detached, initialised AppAnnotationHitHistoriesRecord
     */
    public AppAnnotationHitHistoriesRecord(UUID id, UUID appId, UUID annotationId, String source, String question, UUID accountId, LocalDateTime createdAt, Double score, UUID messageId, String annotationQuestion, String annotationContent) {
        super(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES);

        setId(id);
        setAppId(appId);
        setAnnotationId(annotationId);
        setSource(source);
        setQuestion(question);
        setAccountId(accountId);
        setCreatedAt(createdAt);
        setScore(score);
        setMessageId(messageId);
        setAnnotationQuestion(annotationQuestion);
        setAnnotationContent(annotationContent);
    }
}
