/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.CeleryTasksetmeta;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CeleryTasksetmetaRecord extends UpdatableRecordImpl<CeleryTasksetmetaRecord> implements Record4<Integer, String, byte[], LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.celery_tasksetmeta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.celery_tasksetmeta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.celery_tasksetmeta.taskset_id</code>.
     */
    public void setTasksetId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.celery_tasksetmeta.taskset_id</code>.
     */
    public String getTasksetId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.celery_tasksetmeta.result</code>.
     */
    public void setResult(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.celery_tasksetmeta.result</code>.
     */
    public byte[] getResult() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.celery_tasksetmeta.date_done</code>.
     */
    public void setDateDone(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.celery_tasksetmeta.date_done</code>.
     */
    public LocalDateTime getDateDone() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, byte[], LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, byte[], LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CeleryTasksetmeta.CELERY_TASKSETMETA.ID;
    }

    @Override
    public Field<String> field2() {
        return CeleryTasksetmeta.CELERY_TASKSETMETA.TASKSET_ID;
    }

    @Override
    public Field<byte[]> field3() {
        return CeleryTasksetmeta.CELERY_TASKSETMETA.RESULT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return CeleryTasksetmeta.CELERY_TASKSETMETA.DATE_DONE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTasksetId();
    }

    @Override
    public byte[] component3() {
        return getResult();
    }

    @Override
    public LocalDateTime component4() {
        return getDateDone();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTasksetId();
    }

    @Override
    public byte[] value3() {
        return getResult();
    }

    @Override
    public LocalDateTime value4() {
        return getDateDone();
    }

    @Override
    public CeleryTasksetmetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CeleryTasksetmetaRecord value2(String value) {
        setTasksetId(value);
        return this;
    }

    @Override
    public CeleryTasksetmetaRecord value3(byte[] value) {
        setResult(value);
        return this;
    }

    @Override
    public CeleryTasksetmetaRecord value4(LocalDateTime value) {
        setDateDone(value);
        return this;
    }

    @Override
    public CeleryTasksetmetaRecord values(Integer value1, String value2, byte[] value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CeleryTasksetmetaRecord
     */
    public CeleryTasksetmetaRecord() {
        super(CeleryTasksetmeta.CELERY_TASKSETMETA);
    }

    /**
     * Create a detached, initialised CeleryTasksetmetaRecord
     */
    public CeleryTasksetmetaRecord(Integer id, String tasksetId, byte[] result, LocalDateTime dateDone) {
        super(CeleryTasksetmeta.CELERY_TASKSETMETA);

        setId(id);
        setTasksetId(tasksetId);
        setResult(result);
        setDateDone(dateDone);
    }
}
