/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.CeleryTaskmeta;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CeleryTaskmetaRecord extends UpdatableRecordImpl<CeleryTaskmetaRecord> implements Record12<Integer, String, String, byte[], LocalDateTime, String, String, byte[], byte[], String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.celery_taskmeta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.celery_taskmeta.task_id</code>.
     */
    public void setTaskId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.celery_taskmeta.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.celery_taskmeta.result</code>.
     */
    public void setResult(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.result</code>.
     */
    public byte[] getResult() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.celery_taskmeta.date_done</code>.
     */
    public void setDateDone(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.date_done</code>.
     */
    public LocalDateTime getDateDone() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.celery_taskmeta.traceback</code>.
     */
    public void setTraceback(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.traceback</code>.
     */
    public String getTraceback() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.celery_taskmeta.name</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.name</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.celery_taskmeta.args</code>.
     */
    public void setArgs(byte[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.args</code>.
     */
    public byte[] getArgs() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>public.celery_taskmeta.kwargs</code>.
     */
    public void setKwargs(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.kwargs</code>.
     */
    public byte[] getKwargs() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>public.celery_taskmeta.worker</code>.
     */
    public void setWorker(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.worker</code>.
     */
    public String getWorker() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.celery_taskmeta.retries</code>.
     */
    public void setRetries(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.retries</code>.
     */
    public Integer getRetries() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.celery_taskmeta.queue</code>.
     */
    public void setQueue(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.celery_taskmeta.queue</code>.
     */
    public String getQueue() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, byte[], LocalDateTime, String, String, byte[], byte[], String, Integer, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, byte[], LocalDateTime, String, String, byte[], byte[], String, Integer, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CeleryTaskmeta.CELERY_TASKMETA.ID;
    }

    @Override
    public Field<String> field2() {
        return CeleryTaskmeta.CELERY_TASKMETA.TASK_ID;
    }

    @Override
    public Field<String> field3() {
        return CeleryTaskmeta.CELERY_TASKMETA.STATUS;
    }

    @Override
    public Field<byte[]> field4() {
        return CeleryTaskmeta.CELERY_TASKMETA.RESULT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CeleryTaskmeta.CELERY_TASKMETA.DATE_DONE;
    }

    @Override
    public Field<String> field6() {
        return CeleryTaskmeta.CELERY_TASKMETA.TRACEBACK;
    }

    @Override
    public Field<String> field7() {
        return CeleryTaskmeta.CELERY_TASKMETA.NAME;
    }

    @Override
    public Field<byte[]> field8() {
        return CeleryTaskmeta.CELERY_TASKMETA.ARGS;
    }

    @Override
    public Field<byte[]> field9() {
        return CeleryTaskmeta.CELERY_TASKMETA.KWARGS;
    }

    @Override
    public Field<String> field10() {
        return CeleryTaskmeta.CELERY_TASKMETA.WORKER;
    }

    @Override
    public Field<Integer> field11() {
        return CeleryTaskmeta.CELERY_TASKMETA.RETRIES;
    }

    @Override
    public Field<String> field12() {
        return CeleryTaskmeta.CELERY_TASKMETA.QUEUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTaskId();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public byte[] component4() {
        return getResult();
    }

    @Override
    public LocalDateTime component5() {
        return getDateDone();
    }

    @Override
    public String component6() {
        return getTraceback();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public byte[] component8() {
        return getArgs();
    }

    @Override
    public byte[] component9() {
        return getKwargs();
    }

    @Override
    public String component10() {
        return getWorker();
    }

    @Override
    public Integer component11() {
        return getRetries();
    }

    @Override
    public String component12() {
        return getQueue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTaskId();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public byte[] value4() {
        return getResult();
    }

    @Override
    public LocalDateTime value5() {
        return getDateDone();
    }

    @Override
    public String value6() {
        return getTraceback();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public byte[] value8() {
        return getArgs();
    }

    @Override
    public byte[] value9() {
        return getKwargs();
    }

    @Override
    public String value10() {
        return getWorker();
    }

    @Override
    public Integer value11() {
        return getRetries();
    }

    @Override
    public String value12() {
        return getQueue();
    }

    @Override
    public CeleryTaskmetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value2(String value) {
        setTaskId(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value4(byte[] value) {
        setResult(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value5(LocalDateTime value) {
        setDateDone(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value6(String value) {
        setTraceback(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value8(byte[] value) {
        setArgs(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value9(byte[] value) {
        setKwargs(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value10(String value) {
        setWorker(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value11(Integer value) {
        setRetries(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord value12(String value) {
        setQueue(value);
        return this;
    }

    @Override
    public CeleryTaskmetaRecord values(Integer value1, String value2, String value3, byte[] value4, LocalDateTime value5, String value6, String value7, byte[] value8, byte[] value9, String value10, Integer value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CeleryTaskmetaRecord
     */
    public CeleryTaskmetaRecord() {
        super(CeleryTaskmeta.CELERY_TASKMETA);
    }

    /**
     * Create a detached, initialised CeleryTaskmetaRecord
     */
    public CeleryTaskmetaRecord(Integer id, String taskId, String status, byte[] result, LocalDateTime dateDone, String traceback, String name, byte[] args, byte[] kwargs, String worker, Integer retries, String queue) {
        super(CeleryTaskmeta.CELERY_TASKMETA);

        setId(id);
        setTaskId(taskId);
        setStatus(status);
        setResult(result);
        setDateDone(dateDone);
        setTraceback(traceback);
        setName(name);
        setArgs(args);
        setKwargs(kwargs);
        setWorker(worker);
        setRetries(retries);
        setQueue(queue);
    }
}
