/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.DatasetProcessRules;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetProcessRulesRecord extends UpdatableRecordImpl<DatasetProcessRulesRecord> implements Record6<UUID, UUID, String, String, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dataset_process_rules.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.dataset_process_rules.dataset_id</code>.
     */
    public void setDatasetId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.dataset_id</code>.
     */
    public UUID getDatasetId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.dataset_process_rules.mode</code>.
     */
    public void setMode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.mode</code>.
     */
    public String getMode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.dataset_process_rules.rules</code>.
     */
    public void setRules(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.rules</code>.
     */
    public String getRules() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.dataset_process_rules.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.dataset_process_rules.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.dataset_process_rules.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, UUID, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, String, String, UUID, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.DATASET_ID;
    }

    @Override
    public Field<String> field3() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.MODE;
    }

    @Override
    public Field<String> field4() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.RULES;
    }

    @Override
    public Field<UUID> field5() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return DatasetProcessRules.DATASET_PROCESS_RULES.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getDatasetId();
    }

    @Override
    public String component3() {
        return getMode();
    }

    @Override
    public String component4() {
        return getRules();
    }

    @Override
    public UUID component5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getDatasetId();
    }

    @Override
    public String value3() {
        return getMode();
    }

    @Override
    public String value4() {
        return getRules();
    }

    @Override
    public UUID value5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public DatasetProcessRulesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord value2(UUID value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord value3(String value) {
        setMode(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord value4(String value) {
        setRules(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord value5(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DatasetProcessRulesRecord values(UUID value1, UUID value2, String value3, String value4, UUID value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetProcessRulesRecord
     */
    public DatasetProcessRulesRecord() {
        super(DatasetProcessRules.DATASET_PROCESS_RULES);
    }

    /**
     * Create a detached, initialised DatasetProcessRulesRecord
     */
    public DatasetProcessRulesRecord(UUID id, UUID datasetId, String mode, String rules, UUID createdBy, LocalDateTime createdAt) {
        super(DatasetProcessRules.DATASET_PROCESS_RULES);

        setId(id);
        setDatasetId(datasetId);
        setMode(mode);
        setRules(rules);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
    }
}
