/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.DatasetRetrieverResources;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetRetrieverResourcesRecord extends UpdatableRecordImpl<DatasetRetrieverResourcesRecord> implements Record18<UUID, UUID, Integer, UUID, String, UUID, String, String, UUID, Double, String, Integer, Integer, Integer, String, String, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dataset_retriever_resources.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.message_id</code>.
     */
    public void setMessageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.message_id</code>.
     */
    public UUID getMessageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.position</code>.
     */
    public void setPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.dataset_id</code>.
     */
    public void setDatasetId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.dataset_id</code>.
     */
    public UUID getDatasetId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.dataset_name</code>.
     */
    public void setDatasetName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.dataset_name</code>.
     */
    public String getDatasetName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.document_id</code>.
     */
    public void setDocumentId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.document_id</code>.
     */
    public UUID getDocumentId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.document_name</code>.
     */
    public void setDocumentName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.document_name</code>.
     */
    public String getDocumentName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.data_source_type</code>.
     */
    public void setDataSourceType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.data_source_type</code>.
     */
    public String getDataSourceType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.segment_id</code>.
     */
    public void setSegmentId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.segment_id</code>.
     */
    public UUID getSegmentId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.score</code>.
     */
    public void setScore(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.score</code>.
     */
    public Double getScore() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.content</code>.
     */
    public void setContent(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.content</code>.
     */
    public String getContent() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.hit_count</code>.
     */
    public void setHitCount(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.hit_count</code>.
     */
    public Integer getHitCount() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.word_count</code>.
     */
    public void setWordCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.word_count</code>.
     */
    public Integer getWordCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.segment_position</code>.
     */
    public void setSegmentPosition(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.segment_position</code>.
     */
    public Integer getSegmentPosition() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.index_node_hash</code>.
     */
    public void setIndexNodeHash(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.index_node_hash</code>.
     */
    public String getIndexNodeHash() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.retriever_from</code>.
     */
    public void setRetrieverFrom(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.retriever_from</code>.
     */
    public String getRetrieverFrom() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(16);
    }

    /**
     * Setter for <code>public.dataset_retriever_resources.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.dataset_retriever_resources.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<UUID, UUID, Integer, UUID, String, UUID, String, String, UUID, Double, String, Integer, Integer, Integer, String, String, UUID, LocalDateTime> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<UUID, UUID, Integer, UUID, String, UUID, String, String, UUID, Double, String, Integer, Integer, Integer, String, String, UUID, LocalDateTime> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.MESSAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.POSITION;
    }

    @Override
    public Field<UUID> field4() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.DATASET_ID;
    }

    @Override
    public Field<String> field5() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.DATASET_NAME;
    }

    @Override
    public Field<UUID> field6() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.DOCUMENT_ID;
    }

    @Override
    public Field<String> field7() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.DOCUMENT_NAME;
    }

    @Override
    public Field<String> field8() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.DATA_SOURCE_TYPE;
    }

    @Override
    public Field<UUID> field9() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.SEGMENT_ID;
    }

    @Override
    public Field<Double> field10() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.SCORE;
    }

    @Override
    public Field<String> field11() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.CONTENT;
    }

    @Override
    public Field<Integer> field12() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.HIT_COUNT;
    }

    @Override
    public Field<Integer> field13() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.WORD_COUNT;
    }

    @Override
    public Field<Integer> field14() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.SEGMENT_POSITION;
    }

    @Override
    public Field<String> field15() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.INDEX_NODE_HASH;
    }

    @Override
    public Field<String> field16() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.RETRIEVER_FROM;
    }

    @Override
    public Field<UUID> field17() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getMessageId();
    }

    @Override
    public Integer component3() {
        return getPosition();
    }

    @Override
    public UUID component4() {
        return getDatasetId();
    }

    @Override
    public String component5() {
        return getDatasetName();
    }

    @Override
    public UUID component6() {
        return getDocumentId();
    }

    @Override
    public String component7() {
        return getDocumentName();
    }

    @Override
    public String component8() {
        return getDataSourceType();
    }

    @Override
    public UUID component9() {
        return getSegmentId();
    }

    @Override
    public Double component10() {
        return getScore();
    }

    @Override
    public String component11() {
        return getContent();
    }

    @Override
    public Integer component12() {
        return getHitCount();
    }

    @Override
    public Integer component13() {
        return getWordCount();
    }

    @Override
    public Integer component14() {
        return getSegmentPosition();
    }

    @Override
    public String component15() {
        return getIndexNodeHash();
    }

    @Override
    public String component16() {
        return getRetrieverFrom();
    }

    @Override
    public UUID component17() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component18() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getMessageId();
    }

    @Override
    public Integer value3() {
        return getPosition();
    }

    @Override
    public UUID value4() {
        return getDatasetId();
    }

    @Override
    public String value5() {
        return getDatasetName();
    }

    @Override
    public UUID value6() {
        return getDocumentId();
    }

    @Override
    public String value7() {
        return getDocumentName();
    }

    @Override
    public String value8() {
        return getDataSourceType();
    }

    @Override
    public UUID value9() {
        return getSegmentId();
    }

    @Override
    public Double value10() {
        return getScore();
    }

    @Override
    public String value11() {
        return getContent();
    }

    @Override
    public Integer value12() {
        return getHitCount();
    }

    @Override
    public Integer value13() {
        return getWordCount();
    }

    @Override
    public Integer value14() {
        return getSegmentPosition();
    }

    @Override
    public String value15() {
        return getIndexNodeHash();
    }

    @Override
    public String value16() {
        return getRetrieverFrom();
    }

    @Override
    public UUID value17() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value18() {
        return getCreatedAt();
    }

    @Override
    public DatasetRetrieverResourcesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value2(UUID value) {
        setMessageId(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value3(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value4(UUID value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value5(String value) {
        setDatasetName(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value6(UUID value) {
        setDocumentId(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value7(String value) {
        setDocumentName(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value8(String value) {
        setDataSourceType(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value9(UUID value) {
        setSegmentId(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value10(Double value) {
        setScore(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value11(String value) {
        setContent(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value12(Integer value) {
        setHitCount(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value13(Integer value) {
        setWordCount(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value14(Integer value) {
        setSegmentPosition(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value15(String value) {
        setIndexNodeHash(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value16(String value) {
        setRetrieverFrom(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value17(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord value18(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DatasetRetrieverResourcesRecord values(UUID value1, UUID value2, Integer value3, UUID value4, String value5, UUID value6, String value7, String value8, UUID value9, Double value10, String value11, Integer value12, Integer value13, Integer value14, String value15, String value16, UUID value17, LocalDateTime value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetRetrieverResourcesRecord
     */
    public DatasetRetrieverResourcesRecord() {
        super(DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES);
    }

    /**
     * Create a detached, initialised DatasetRetrieverResourcesRecord
     */
    public DatasetRetrieverResourcesRecord(UUID id, UUID messageId, Integer position, UUID datasetId, String datasetName, UUID documentId, String documentName, String dataSourceType, UUID segmentId, Double score, String content, Integer hitCount, Integer wordCount, Integer segmentPosition, String indexNodeHash, String retrieverFrom, UUID createdBy, LocalDateTime createdAt) {
        super(DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES);

        setId(id);
        setMessageId(messageId);
        setPosition(position);
        setDatasetId(datasetId);
        setDatasetName(datasetName);
        setDocumentId(documentId);
        setDocumentName(documentName);
        setDataSourceType(dataSourceType);
        setSegmentId(segmentId);
        setScore(score);
        setContent(content);
        setHitCount(hitCount);
        setWordCount(wordCount);
        setSegmentPosition(segmentPosition);
        setIndexNodeHash(indexNodeHash);
        setRetrieverFrom(retrieverFrom);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
    }
}
