/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.Datasets;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetsRecord extends UpdatableRecordImpl<DatasetsRecord> implements Record17<UUID, UUID, String, String, String, String, String, String, String, UUID, LocalDateTime, UUID, LocalDateTime, String, String, UUID, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.datasets.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.datasets.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.datasets.tenant_id</code>.
     */
    public void setTenantId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.datasets.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.datasets.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.datasets.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.datasets.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.datasets.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.datasets.provider</code>.
     */
    public void setProvider(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.datasets.provider</code>.
     */
    public String getProvider() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.datasets.permission</code>.
     */
    public void setPermission(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.datasets.permission</code>.
     */
    public String getPermission() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.datasets.data_source_type</code>.
     */
    public void setDataSourceType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.datasets.data_source_type</code>.
     */
    public String getDataSourceType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.datasets.indexing_technique</code>.
     */
    public void setIndexingTechnique(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.datasets.indexing_technique</code>.
     */
    public String getIndexingTechnique() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.datasets.index_struct</code>.
     */
    public void setIndexStruct(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.datasets.index_struct</code>.
     */
    public String getIndexStruct() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.datasets.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.datasets.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.datasets.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.datasets.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.datasets.updated_by</code>.
     */
    public void setUpdatedBy(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.datasets.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.datasets.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.datasets.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.datasets.embedding_model</code>.
     */
    public void setEmbeddingModel(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.datasets.embedding_model</code>.
     */
    public String getEmbeddingModel() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.datasets.embedding_model_provider</code>.
     */
    public void setEmbeddingModelProvider(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.datasets.embedding_model_provider</code>.
     */
    public String getEmbeddingModelProvider() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.datasets.collection_binding_id</code>.
     */
    public void setCollectionBindingId(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.datasets.collection_binding_id</code>.
     */
    public UUID getCollectionBindingId() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>public.datasets.retrieval_model</code>.
     */
    public void setRetrievalModel(JSONB value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.datasets.retrieval_model</code>.
     */
    public JSONB getRetrievalModel() {
        return (JSONB) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<UUID, UUID, String, String, String, String, String, String, String, UUID, LocalDateTime, UUID, LocalDateTime, String, String, UUID, JSONB> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<UUID, UUID, String, String, String, String, String, String, String, UUID, LocalDateTime, UUID, LocalDateTime, String, String, UUID, JSONB> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Datasets.DATASETS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Datasets.DATASETS.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return Datasets.DATASETS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Datasets.DATASETS.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Datasets.DATASETS.PROVIDER;
    }

    @Override
    public Field<String> field6() {
        return Datasets.DATASETS.PERMISSION;
    }

    @Override
    public Field<String> field7() {
        return Datasets.DATASETS.DATA_SOURCE_TYPE;
    }

    @Override
    public Field<String> field8() {
        return Datasets.DATASETS.INDEXING_TECHNIQUE;
    }

    @Override
    public Field<String> field9() {
        return Datasets.DATASETS.INDEX_STRUCT;
    }

    @Override
    public Field<UUID> field10() {
        return Datasets.DATASETS.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Datasets.DATASETS.CREATED_AT;
    }

    @Override
    public Field<UUID> field12() {
        return Datasets.DATASETS.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Datasets.DATASETS.UPDATED_AT;
    }

    @Override
    public Field<String> field14() {
        return Datasets.DATASETS.EMBEDDING_MODEL;
    }

    @Override
    public Field<String> field15() {
        return Datasets.DATASETS.EMBEDDING_MODEL_PROVIDER;
    }

    @Override
    public Field<UUID> field16() {
        return Datasets.DATASETS.COLLECTION_BINDING_ID;
    }

    @Override
    public Field<JSONB> field17() {
        return Datasets.DATASETS.RETRIEVAL_MODEL;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getProvider();
    }

    @Override
    public String component6() {
        return getPermission();
    }

    @Override
    public String component7() {
        return getDataSourceType();
    }

    @Override
    public String component8() {
        return getIndexingTechnique();
    }

    @Override
    public String component9() {
        return getIndexStruct();
    }

    @Override
    public UUID component10() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedAt();
    }

    @Override
    public UUID component12() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdatedAt();
    }

    @Override
    public String component14() {
        return getEmbeddingModel();
    }

    @Override
    public String component15() {
        return getEmbeddingModelProvider();
    }

    @Override
    public UUID component16() {
        return getCollectionBindingId();
    }

    @Override
    public JSONB component17() {
        return getRetrievalModel();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getProvider();
    }

    @Override
    public String value6() {
        return getPermission();
    }

    @Override
    public String value7() {
        return getDataSourceType();
    }

    @Override
    public String value8() {
        return getIndexingTechnique();
    }

    @Override
    public String value9() {
        return getIndexStruct();
    }

    @Override
    public UUID value10() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedAt();
    }

    @Override
    public UUID value12() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdatedAt();
    }

    @Override
    public String value14() {
        return getEmbeddingModel();
    }

    @Override
    public String value15() {
        return getEmbeddingModelProvider();
    }

    @Override
    public UUID value16() {
        return getCollectionBindingId();
    }

    @Override
    public JSONB value17() {
        return getRetrievalModel();
    }

    @Override
    public DatasetsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetsRecord value2(UUID value) {
        setTenantId(value);
        return this;
    }

    @Override
    public DatasetsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public DatasetsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DatasetsRecord value5(String value) {
        setProvider(value);
        return this;
    }

    @Override
    public DatasetsRecord value6(String value) {
        setPermission(value);
        return this;
    }

    @Override
    public DatasetsRecord value7(String value) {
        setDataSourceType(value);
        return this;
    }

    @Override
    public DatasetsRecord value8(String value) {
        setIndexingTechnique(value);
        return this;
    }

    @Override
    public DatasetsRecord value9(String value) {
        setIndexStruct(value);
        return this;
    }

    @Override
    public DatasetsRecord value10(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DatasetsRecord value11(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DatasetsRecord value12(UUID value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public DatasetsRecord value13(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public DatasetsRecord value14(String value) {
        setEmbeddingModel(value);
        return this;
    }

    @Override
    public DatasetsRecord value15(String value) {
        setEmbeddingModelProvider(value);
        return this;
    }

    @Override
    public DatasetsRecord value16(UUID value) {
        setCollectionBindingId(value);
        return this;
    }

    @Override
    public DatasetsRecord value17(JSONB value) {
        setRetrievalModel(value);
        return this;
    }

    @Override
    public DatasetsRecord values(UUID value1, UUID value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, UUID value10, LocalDateTime value11, UUID value12, LocalDateTime value13, String value14, String value15, UUID value16, JSONB value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetsRecord
     */
    public DatasetsRecord() {
        super(Datasets.DATASETS);
    }

    /**
     * Create a detached, initialised DatasetsRecord
     */
    public DatasetsRecord(UUID id, UUID tenantId, String name, String description, String provider, String permission, String dataSourceType, String indexingTechnique, String indexStruct, UUID createdBy, LocalDateTime createdAt, UUID updatedBy, LocalDateTime updatedAt, String embeddingModel, String embeddingModelProvider, UUID collectionBindingId, JSONB retrievalModel) {
        super(Datasets.DATASETS);

        setId(id);
        setTenantId(tenantId);
        setName(name);
        setDescription(description);
        setProvider(provider);
        setPermission(permission);
        setDataSourceType(dataSourceType);
        setIndexingTechnique(indexingTechnique);
        setIndexStruct(indexStruct);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        setEmbeddingModel(embeddingModel);
        setEmbeddingModelProvider(embeddingModelProvider);
        setCollectionBindingId(collectionBindingId);
        setRetrievalModel(retrievalModel);
    }
}
