/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.Embeddings;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmbeddingsRecord extends UpdatableRecordImpl<EmbeddingsRecord> implements Record5<UUID, String, byte[], LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.embeddings.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.embeddings.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.embeddings.hash</code>.
     */
    public void setHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.embeddings.hash</code>.
     */
    public String getHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.embeddings.embedding</code>.
     */
    public void setEmbedding(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.embeddings.embedding</code>.
     */
    public byte[] getEmbedding() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.embeddings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.embeddings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.embeddings.model_name</code>.
     */
    public void setModelName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.embeddings.model_name</code>.
     */
    public String getModelName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, byte[], LocalDateTime, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, byte[], LocalDateTime, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Embeddings.EMBEDDINGS.ID;
    }

    @Override
    public Field<String> field2() {
        return Embeddings.EMBEDDINGS.HASH;
    }

    @Override
    public Field<byte[]> field3() {
        return Embeddings.EMBEDDINGS.EMBEDDING;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Embeddings.EMBEDDINGS.CREATED_AT;
    }

    @Override
    public Field<String> field5() {
        return Embeddings.EMBEDDINGS.MODEL_NAME;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHash();
    }

    @Override
    public byte[] component3() {
        return getEmbedding();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public String component5() {
        return getModelName();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHash();
    }

    @Override
    public byte[] value3() {
        return getEmbedding();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public String value5() {
        return getModelName();
    }

    @Override
    public EmbeddingsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EmbeddingsRecord value2(String value) {
        setHash(value);
        return this;
    }

    @Override
    public EmbeddingsRecord value3(byte[] value) {
        setEmbedding(value);
        return this;
    }

    @Override
    public EmbeddingsRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EmbeddingsRecord value5(String value) {
        setModelName(value);
        return this;
    }

    @Override
    public EmbeddingsRecord values(UUID value1, String value2, byte[] value3, LocalDateTime value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmbeddingsRecord
     */
    public EmbeddingsRecord() {
        super(Embeddings.EMBEDDINGS);
    }

    /**
     * Create a detached, initialised EmbeddingsRecord
     */
    public EmbeddingsRecord(UUID id, String hash, byte[] embedding, LocalDateTime createdAt, String modelName) {
        super(Embeddings.EMBEDDINGS);

        setId(id);
        setHash(hash);
        setEmbedding(embedding);
        setCreatedAt(createdAt);
        setModelName(modelName);
    }
}
