/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.records;


import com.bonc.lops.jooq.tables.ToolBuiltinProviders;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ToolBuiltinProvidersRecord extends UpdatableRecordImpl<ToolBuiltinProvidersRecord> implements Record7<UUID, UUID, UUID, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tool_builtin_providers.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.tenant_id</code>.
     */
    public void setTenantId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.provider</code>.
     */
    public void setProvider(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.provider</code>.
     */
    public String getProvider() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.encrypted_credentials</code>.
     */
    public void setEncryptedCredentials(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.encrypted_credentials</code>.
     */
    public String getEncryptedCredentials() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.tool_builtin_providers.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tool_builtin_providers.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, UUID, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, UUID, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.TENANT_ID;
    }

    @Override
    public Field<UUID> field3() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.PROVIDER;
    }

    @Override
    public Field<String> field5() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.ENCRYPTED_CREDENTIALS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getTenantId();
    }

    @Override
    public UUID component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getProvider();
    }

    @Override
    public String component5() {
        return getEncryptedCredentials();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getTenantId();
    }

    @Override
    public UUID value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getProvider();
    }

    @Override
    public String value5() {
        return getEncryptedCredentials();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public ToolBuiltinProvidersRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value2(UUID value) {
        setTenantId(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value3(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value4(String value) {
        setProvider(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value5(String value) {
        setEncryptedCredentials(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ToolBuiltinProvidersRecord values(UUID value1, UUID value2, UUID value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ToolBuiltinProvidersRecord
     */
    public ToolBuiltinProvidersRecord() {
        super(ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS);
    }

    /**
     * Create a detached, initialised ToolBuiltinProvidersRecord
     */
    public ToolBuiltinProvidersRecord(UUID id, UUID tenantId, UUID userId, String provider, String encryptedCredentials, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS);

        setId(id);
        setTenantId(tenantId);
        setUserId(userId);
        setProvider(provider);
        setEncryptedCredentials(encryptedCredentials);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
