/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.AppAnnotationHitHistories;
import com.bonc.lops.jooq.tables.records.AppAnnotationHitHistoriesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AppAnnotationHitHistoriesDao extends DAOImpl<AppAnnotationHitHistoriesRecord, com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories, UUID> {

    /**
     * Create a new AppAnnotationHitHistoriesDao without any configuration
     */
    public AppAnnotationHitHistoriesDao() {
        super(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES, com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories.class);
    }

    /**
     * Create a new AppAnnotationHitHistoriesDao with an attached configuration
     */
    @Autowired
    public AppAnnotationHitHistoriesDao(Configuration configuration) {
        super(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES, com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories.class, configuration);
    }

    @Override
    public UUID getId(com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchById(UUID... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories fetchOneById(UUID value) {
        return fetchOne(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ID, value);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfAppId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByAppId(UUID... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.APP_ID, values);
    }

    /**
     * Fetch records that have <code>annotation_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfAnnotationId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>annotation_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByAnnotationId(UUID... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_ID, values);
    }

    /**
     * Fetch records that have <code>source BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfSource(String lowerInclusive, String upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchBySource(String... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SOURCE, values);
    }

    /**
     * Fetch records that have <code>question BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfQuestion(String lowerInclusive, String upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.QUESTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>question IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByQuestion(String... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.QUESTION, values);
    }

    /**
     * Fetch records that have <code>account_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfAccountId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ACCOUNT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByAccountId(UUID... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ACCOUNT_ID, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>score BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfScore(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SCORE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>score IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByScore(Double... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.SCORE, values);
    }

    /**
     * Fetch records that have <code>message_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfMessageId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.MESSAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>message_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByMessageId(UUID... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.MESSAGE_ID, values);
    }

    /**
     * Fetch records that have <code>annotation_question BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfAnnotationQuestion(String lowerInclusive, String upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_QUESTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>annotation_question IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByAnnotationQuestion(String... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_QUESTION, values);
    }

    /**
     * Fetch records that have <code>annotation_content BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchRangeOfAnnotationContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>annotation_content IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.AppAnnotationHitHistories> fetchByAnnotationContent(String... values) {
        return fetch(AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES.ANNOTATION_CONTENT, values);
    }
}
