/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.DifySetups;
import com.bonc.lops.jooq.tables.records.DifySetupsRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DifySetupsDao extends DAOImpl<DifySetupsRecord, com.bonc.lops.jooq.tables.pojos.DifySetups, String> {

    /**
     * Create a new DifySetupsDao without any configuration
     */
    public DifySetupsDao() {
        super(DifySetups.DIFY_SETUPS, com.bonc.lops.jooq.tables.pojos.DifySetups.class);
    }

    /**
     * Create a new DifySetupsDao with an attached configuration
     */
    @Autowired
    public DifySetupsDao(Configuration configuration) {
        super(DifySetups.DIFY_SETUPS, com.bonc.lops.jooq.tables.pojos.DifySetups.class, configuration);
    }

    @Override
    public String getId(com.bonc.lops.jooq.tables.pojos.DifySetups object) {
        return object.getVersion();
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.DifySetups> fetchRangeOfVersion(String lowerInclusive, String upperInclusive) {
        return fetchRange(DifySetups.DIFY_SETUPS.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.DifySetups> fetchByVersion(String... values) {
        return fetch(DifySetups.DIFY_SETUPS.VERSION, values);
    }

    /**
     * Fetch a unique record that has <code>version = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.DifySetups fetchOneByVersion(String value) {
        return fetchOne(DifySetups.DIFY_SETUPS.VERSION, value);
    }

    /**
     * Fetch records that have <code>setup_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.DifySetups> fetchRangeOfSetupAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(DifySetups.DIFY_SETUPS.SETUP_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>setup_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.DifySetups> fetchBySetupAt(LocalDateTime... values) {
        return fetch(DifySetups.DIFY_SETUPS.SETUP_AT, values);
    }
}
