/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.InstalledApps;
import com.bonc.lops.jooq.tables.records.InstalledAppsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class InstalledAppsDao extends DAOImpl<InstalledAppsRecord, com.bonc.lops.jooq.tables.pojos.InstalledApps, UUID> {

    /**
     * Create a new InstalledAppsDao without any configuration
     */
    public InstalledAppsDao() {
        super(InstalledApps.INSTALLED_APPS, com.bonc.lops.jooq.tables.pojos.InstalledApps.class);
    }

    /**
     * Create a new InstalledAppsDao with an attached configuration
     */
    @Autowired
    public InstalledAppsDao(Configuration configuration) {
        super(InstalledApps.INSTALLED_APPS, com.bonc.lops.jooq.tables.pojos.InstalledApps.class, configuration);
    }

    @Override
    public UUID getId(com.bonc.lops.jooq.tables.pojos.InstalledApps object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchById(UUID... values) {
        return fetch(InstalledApps.INSTALLED_APPS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.InstalledApps fetchOneById(UUID value) {
        return fetchOne(InstalledApps.INSTALLED_APPS.ID, value);
    }

    /**
     * Fetch records that have <code>tenant_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfTenantId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.TENANT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tenant_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByTenantId(UUID... values) {
        return fetch(InstalledApps.INSTALLED_APPS.TENANT_ID, values);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfAppId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByAppId(UUID... values) {
        return fetch(InstalledApps.INSTALLED_APPS.APP_ID, values);
    }

    /**
     * Fetch records that have <code>app_owner_tenant_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfAppOwnerTenantId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.APP_OWNER_TENANT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_owner_tenant_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByAppOwnerTenantId(UUID... values) {
        return fetch(InstalledApps.INSTALLED_APPS.APP_OWNER_TENANT_ID, values);
    }

    /**
     * Fetch records that have <code>position BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfPosition(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.POSITION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>position IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByPosition(Integer... values) {
        return fetch(InstalledApps.INSTALLED_APPS.POSITION, values);
    }

    /**
     * Fetch records that have <code>is_pinned BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfIsPinned(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.IS_PINNED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_pinned IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByIsPinned(Boolean... values) {
        return fetch(InstalledApps.INSTALLED_APPS.IS_PINNED, values);
    }

    /**
     * Fetch records that have <code>last_used_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfLastUsedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.LAST_USED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_used_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByLastUsedAt(LocalDateTime... values) {
        return fetch(InstalledApps.INSTALLED_APPS.LAST_USED_AT, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(InstalledApps.INSTALLED_APPS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.InstalledApps> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(InstalledApps.INSTALLED_APPS.CREATED_AT, values);
    }
}
