/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.SavedMessages;
import com.bonc.lops.jooq.tables.records.SavedMessagesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SavedMessagesDao extends DAOImpl<SavedMessagesRecord, com.bonc.lops.jooq.tables.pojos.SavedMessages, UUID> {

    /**
     * Create a new SavedMessagesDao without any configuration
     */
    public SavedMessagesDao() {
        super(SavedMessages.SAVED_MESSAGES, com.bonc.lops.jooq.tables.pojos.SavedMessages.class);
    }

    /**
     * Create a new SavedMessagesDao with an attached configuration
     */
    @Autowired
    public SavedMessagesDao(Configuration configuration) {
        super(SavedMessages.SAVED_MESSAGES, com.bonc.lops.jooq.tables.pojos.SavedMessages.class, configuration);
    }

    @Override
    public UUID getId(com.bonc.lops.jooq.tables.pojos.SavedMessages object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchById(UUID... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.SavedMessages fetchOneById(UUID value) {
        return fetchOne(SavedMessages.SAVED_MESSAGES.ID, value);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfAppId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchByAppId(UUID... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.APP_ID, values);
    }

    /**
     * Fetch records that have <code>message_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfMessageId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.MESSAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>message_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchByMessageId(UUID... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.MESSAGE_ID, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchByCreatedBy(UUID... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>created_by_role BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchRangeOfCreatedByRole(String lowerInclusive, String upperInclusive) {
        return fetchRange(SavedMessages.SAVED_MESSAGES.CREATED_BY_ROLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by_role IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.SavedMessages> fetchByCreatedByRole(String... values) {
        return fetch(SavedMessages.SAVED_MESSAGES.CREATED_BY_ROLE, values);
    }
}
