/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.Sites;
import com.bonc.lops.jooq.tables.records.SitesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SitesDao extends DAOImpl<SitesRecord, com.bonc.lops.jooq.tables.pojos.Sites, UUID> {

    /**
     * Create a new SitesDao without any configuration
     */
    public SitesDao() {
        super(Sites.SITES, com.bonc.lops.jooq.tables.pojos.Sites.class);
    }

    /**
     * Create a new SitesDao with an attached configuration
     */
    @Autowired
    public SitesDao(Configuration configuration) {
        super(Sites.SITES, com.bonc.lops.jooq.tables.pojos.Sites.class, configuration);
    }

    @Override
    public UUID getId(com.bonc.lops.jooq.tables.pojos.Sites object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Sites.SITES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchById(UUID... values) {
        return fetch(Sites.SITES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.Sites fetchOneById(UUID value) {
        return fetchOne(Sites.SITES.ID, value);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfAppId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Sites.SITES.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByAppId(UUID... values) {
        return fetch(Sites.SITES.APP_ID, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByTitle(String... values) {
        return fetch(Sites.SITES.TITLE, values);
    }

    /**
     * Fetch records that have <code>icon BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfIcon(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.ICON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByIcon(String... values) {
        return fetch(Sites.SITES.ICON, values);
    }

    /**
     * Fetch records that have <code>icon_background BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfIconBackground(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.ICON_BACKGROUND, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icon_background IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByIconBackground(String... values) {
        return fetch(Sites.SITES.ICON_BACKGROUND, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByDescription(String... values) {
        return fetch(Sites.SITES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>default_language BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfDefaultLanguage(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.DEFAULT_LANGUAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>default_language IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByDefaultLanguage(String... values) {
        return fetch(Sites.SITES.DEFAULT_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>copyright BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfCopyright(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.COPYRIGHT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>copyright IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByCopyright(String... values) {
        return fetch(Sites.SITES.COPYRIGHT, values);
    }

    /**
     * Fetch records that have <code>privacy_policy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfPrivacyPolicy(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.PRIVACY_POLICY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>privacy_policy IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByPrivacyPolicy(String... values) {
        return fetch(Sites.SITES.PRIVACY_POLICY, values);
    }

    /**
     * Fetch records that have <code>customize_domain BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfCustomizeDomain(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.CUSTOMIZE_DOMAIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>customize_domain IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByCustomizeDomain(String... values) {
        return fetch(Sites.SITES.CUSTOMIZE_DOMAIN, values);
    }

    /**
     * Fetch records that have <code>customize_token_strategy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfCustomizeTokenStrategy(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.CUSTOMIZE_TOKEN_STRATEGY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>customize_token_strategy IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByCustomizeTokenStrategy(String... values) {
        return fetch(Sites.SITES.CUSTOMIZE_TOKEN_STRATEGY, values);
    }

    /**
     * Fetch records that have <code>prompt_public BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfPromptPublic(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Sites.SITES.PROMPT_PUBLIC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>prompt_public IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByPromptPublic(Boolean... values) {
        return fetch(Sites.SITES.PROMPT_PUBLIC, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByStatus(String... values) {
        return fetch(Sites.SITES.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Sites.SITES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Sites.SITES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Sites.SITES.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Sites.SITES.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sites.SITES.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.Sites> fetchByCode(String... values) {
        return fetch(Sites.SITES.CODE, values);
    }
}
