/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.daos;


import com.bonc.lops.jooq.tables.ToolPublishedApps;
import com.bonc.lops.jooq.tables.records.ToolPublishedAppsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ToolPublishedAppsDao extends DAOImpl<ToolPublishedAppsRecord, com.bonc.lops.jooq.tables.pojos.ToolPublishedApps, UUID> {

    /**
     * Create a new ToolPublishedAppsDao without any configuration
     */
    public ToolPublishedAppsDao() {
        super(ToolPublishedApps.TOOL_PUBLISHED_APPS, com.bonc.lops.jooq.tables.pojos.ToolPublishedApps.class);
    }

    /**
     * Create a new ToolPublishedAppsDao with an attached configuration
     */
    @Autowired
    public ToolPublishedAppsDao(Configuration configuration) {
        super(ToolPublishedApps.TOOL_PUBLISHED_APPS, com.bonc.lops.jooq.tables.pojos.ToolPublishedApps.class, configuration);
    }

    @Override
    public UUID getId(com.bonc.lops.jooq.tables.pojos.ToolPublishedApps object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchById(UUID... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bonc.lops.jooq.tables.pojos.ToolPublishedApps fetchOneById(UUID value) {
        return fetchOne(ToolPublishedApps.TOOL_PUBLISHED_APPS.ID, value);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfAppId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByAppId(UUID... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.APP_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfUserId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByUserId(UUID... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.USER_ID, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByDescription(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>llm_description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfLlmDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.LLM_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>llm_description IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByLlmDescription(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.LLM_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>query_description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfQueryDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.QUERY_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>query_description IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByQueryDescription(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.QUERY_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>query_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfQueryName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.QUERY_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>query_name IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByQueryName(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.QUERY_NAME, values);
    }

    /**
     * Fetch records that have <code>tool_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfToolName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.TOOL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tool_name IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByToolName(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.TOOL_NAME, values);
    }

    /**
     * Fetch records that have <code>author BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfAuthor(String lowerInclusive, String upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.AUTHOR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>author IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByAuthor(String... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.AUTHOR, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ToolPublishedApps.TOOL_PUBLISHED_APPS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.bonc.lops.jooq.tables.pojos.ToolPublishedApps> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(ToolPublishedApps.TOOL_PUBLISHED_APPS.UPDATED_AT, values);
    }
}
