/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables;


import com.bonc.lops.jooq.Indexes;
import com.bonc.lops.jooq.Keys;
import com.bonc.lops.jooq.Public;
import com.bonc.lops.jooq.tables.records.TenantDefaultModelsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TenantDefaultModels extends TableImpl<TenantDefaultModelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tenant_default_models</code>
     */
    public static final TenantDefaultModels TENANT_DEFAULT_MODELS = new TenantDefaultModels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TenantDefaultModelsRecord> getRecordType() {
        return TenantDefaultModelsRecord.class;
    }

    /**
     * The column <code>public.tenant_default_models.id</code>.
     */
    public final TableField<TenantDefaultModelsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.tenant_default_models.tenant_id</code>.
     */
    public final TableField<TenantDefaultModelsRecord, UUID> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenant_default_models.provider_name</code>.
     */
    public final TableField<TenantDefaultModelsRecord, String> PROVIDER_NAME = createField(DSL.name("provider_name"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.tenant_default_models.model_name</code>.
     */
    public final TableField<TenantDefaultModelsRecord, String> MODEL_NAME = createField(DSL.name("model_name"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.tenant_default_models.model_type</code>.
     */
    public final TableField<TenantDefaultModelsRecord, String> MODEL_TYPE = createField(DSL.name("model_type"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.tenant_default_models.created_at</code>.
     */
    public final TableField<TenantDefaultModelsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(0)", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.tenant_default_models.updated_at</code>.
     */
    public final TableField<TenantDefaultModelsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(0)", SQLDataType.LOCALDATETIME)), this, "");

    private TenantDefaultModels(Name alias, Table<TenantDefaultModelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TenantDefaultModels(Name alias, Table<TenantDefaultModelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tenant_default_models</code> table reference
     */
    public TenantDefaultModels(String alias) {
        this(DSL.name(alias), TENANT_DEFAULT_MODELS);
    }

    /**
     * Create an aliased <code>public.tenant_default_models</code> table reference
     */
    public TenantDefaultModels(Name alias) {
        this(alias, TENANT_DEFAULT_MODELS);
    }

    /**
     * Create a <code>public.tenant_default_models</code> table reference
     */
    public TenantDefaultModels() {
        this(DSL.name("tenant_default_models"), null);
    }

    public <O extends Record> TenantDefaultModels(Table<O> child, ForeignKey<O, TenantDefaultModelsRecord> key) {
        super(child, key, TENANT_DEFAULT_MODELS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TENANT_DEFAULT_MODEL_TENANT_ID_PROVIDER_TYPE_IDX);
    }

    @Override
    public UniqueKey<TenantDefaultModelsRecord> getPrimaryKey() {
        return Keys.TENANT_DEFAULT_MODEL_PKEY;
    }

    @Override
    public List<UniqueKey<TenantDefaultModelsRecord>> getKeys() {
        return Arrays.<UniqueKey<TenantDefaultModelsRecord>>asList(Keys.TENANT_DEFAULT_MODEL_PKEY);
    }

    @Override
    public TenantDefaultModels as(String alias) {
        return new TenantDefaultModels(DSL.name(alias), this);
    }

    @Override
    public TenantDefaultModels as(Name alias) {
        return new TenantDefaultModels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TenantDefaultModels rename(String name) {
        return new TenantDefaultModels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TenantDefaultModels rename(Name name) {
        return new TenantDefaultModels(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
