/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq;


import com.bonc.lops.jooq.tables.AccountIntegrates;
import com.bonc.lops.jooq.tables.Accounts;
import com.bonc.lops.jooq.tables.AlembicVersion;
import com.bonc.lops.jooq.tables.ApiBasedExtensions;
import com.bonc.lops.jooq.tables.ApiRequests;
import com.bonc.lops.jooq.tables.ApiTokens;
import com.bonc.lops.jooq.tables.AppAnnotationHitHistories;
import com.bonc.lops.jooq.tables.AppAnnotationSettings;
import com.bonc.lops.jooq.tables.AppDatasetJoins;
import com.bonc.lops.jooq.tables.AppModelConfigs;
import com.bonc.lops.jooq.tables.Apps;
import com.bonc.lops.jooq.tables.CeleryTaskmeta;
import com.bonc.lops.jooq.tables.CeleryTasksetmeta;
import com.bonc.lops.jooq.tables.Conversations;
import com.bonc.lops.jooq.tables.DataSourceBindings;
import com.bonc.lops.jooq.tables.DatasetCollectionBindings;
import com.bonc.lops.jooq.tables.DatasetKeywordTables;
import com.bonc.lops.jooq.tables.DatasetProcessRules;
import com.bonc.lops.jooq.tables.DatasetQueries;
import com.bonc.lops.jooq.tables.DatasetRetrieverResources;
import com.bonc.lops.jooq.tables.Datasets;
import com.bonc.lops.jooq.tables.DifySetups;
import com.bonc.lops.jooq.tables.DocumentSegments;
import com.bonc.lops.jooq.tables.Documents;
import com.bonc.lops.jooq.tables.Embeddings;
import com.bonc.lops.jooq.tables.EndUsers;
import com.bonc.lops.jooq.tables.InstalledApps;
import com.bonc.lops.jooq.tables.InvitationCodes;
import com.bonc.lops.jooq.tables.MessageAgentThoughts;
import com.bonc.lops.jooq.tables.MessageAnnotations;
import com.bonc.lops.jooq.tables.MessageChains;
import com.bonc.lops.jooq.tables.MessageFeedbacks;
import com.bonc.lops.jooq.tables.MessageFiles;
import com.bonc.lops.jooq.tables.Messages;
import com.bonc.lops.jooq.tables.OperationLogs;
import com.bonc.lops.jooq.tables.PinnedConversations;
import com.bonc.lops.jooq.tables.ProviderModels;
import com.bonc.lops.jooq.tables.ProviderOrders;
import com.bonc.lops.jooq.tables.Providers;
import com.bonc.lops.jooq.tables.RecommendedApps;
import com.bonc.lops.jooq.tables.SavedMessages;
import com.bonc.lops.jooq.tables.Sites;
import com.bonc.lops.jooq.tables.TenantAccountJoins;
import com.bonc.lops.jooq.tables.TenantDefaultModels;
import com.bonc.lops.jooq.tables.TenantPreferredModelProviders;
import com.bonc.lops.jooq.tables.Tenants;
import com.bonc.lops.jooq.tables.ToolApiProviders;
import com.bonc.lops.jooq.tables.ToolBuiltinProviders;
import com.bonc.lops.jooq.tables.ToolConversationVariables;
import com.bonc.lops.jooq.tables.ToolFiles;
import com.bonc.lops.jooq.tables.ToolModelInvokes;
import com.bonc.lops.jooq.tables.ToolProviders;
import com.bonc.lops.jooq.tables.ToolPublishedApps;
import com.bonc.lops.jooq.tables.UploadFiles;
import com.bonc.lops.jooq.tables.WorkflowAppLogs;
import com.bonc.lops.jooq.tables.WorkflowNodeExecutions;
import com.bonc.lops.jooq.tables.WorkflowRuns;
import com.bonc.lops.jooq.tables.Workflows;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account_integrates</code>.
     */
    public final AccountIntegrates ACCOUNT_INTEGRATES = AccountIntegrates.ACCOUNT_INTEGRATES;

    /**
     * The table <code>public.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.alembic_version</code>.
     */
    public final AlembicVersion ALEMBIC_VERSION = AlembicVersion.ALEMBIC_VERSION;

    /**
     * The table <code>public.api_based_extensions</code>.
     */
    public final ApiBasedExtensions API_BASED_EXTENSIONS = ApiBasedExtensions.API_BASED_EXTENSIONS;

    /**
     * The table <code>public.api_requests</code>.
     */
    public final ApiRequests API_REQUESTS = ApiRequests.API_REQUESTS;

    /**
     * The table <code>public.api_tokens</code>.
     */
    public final ApiTokens API_TOKENS = ApiTokens.API_TOKENS;

    /**
     * The table <code>public.app_annotation_hit_histories</code>.
     */
    public final AppAnnotationHitHistories APP_ANNOTATION_HIT_HISTORIES = AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES;

    /**
     * The table <code>public.app_annotation_settings</code>.
     */
    public final AppAnnotationSettings APP_ANNOTATION_SETTINGS = AppAnnotationSettings.APP_ANNOTATION_SETTINGS;

    /**
     * The table <code>public.app_dataset_joins</code>.
     */
    public final AppDatasetJoins APP_DATASET_JOINS = AppDatasetJoins.APP_DATASET_JOINS;

    /**
     * The table <code>public.app_model_configs</code>.
     */
    public final AppModelConfigs APP_MODEL_CONFIGS = AppModelConfigs.APP_MODEL_CONFIGS;

    /**
     * The table <code>public.apps</code>.
     */
    public final Apps APPS = Apps.APPS;

    /**
     * The table <code>public.celery_taskmeta</code>.
     */
    public final CeleryTaskmeta CELERY_TASKMETA = CeleryTaskmeta.CELERY_TASKMETA;

    /**
     * The table <code>public.celery_tasksetmeta</code>.
     */
    public final CeleryTasksetmeta CELERY_TASKSETMETA = CeleryTasksetmeta.CELERY_TASKSETMETA;

    /**
     * The table <code>public.conversations</code>.
     */
    public final Conversations CONVERSATIONS = Conversations.CONVERSATIONS;

    /**
     * The table <code>public.data_source_bindings</code>.
     */
    public final DataSourceBindings DATA_SOURCE_BINDINGS = DataSourceBindings.DATA_SOURCE_BINDINGS;

    /**
     * The table <code>public.dataset_collection_bindings</code>.
     */
    public final DatasetCollectionBindings DATASET_COLLECTION_BINDINGS = DatasetCollectionBindings.DATASET_COLLECTION_BINDINGS;

    /**
     * The table <code>public.dataset_keyword_tables</code>.
     */
    public final DatasetKeywordTables DATASET_KEYWORD_TABLES = DatasetKeywordTables.DATASET_KEYWORD_TABLES;

    /**
     * The table <code>public.dataset_process_rules</code>.
     */
    public final DatasetProcessRules DATASET_PROCESS_RULES = DatasetProcessRules.DATASET_PROCESS_RULES;

    /**
     * The table <code>public.dataset_queries</code>.
     */
    public final DatasetQueries DATASET_QUERIES = DatasetQueries.DATASET_QUERIES;

    /**
     * The table <code>public.dataset_retriever_resources</code>.
     */
    public final DatasetRetrieverResources DATASET_RETRIEVER_RESOURCES = DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES;

    /**
     * The table <code>public.datasets</code>.
     */
    public final Datasets DATASETS = Datasets.DATASETS;

    /**
     * The table <code>public.dify_setups</code>.
     */
    public final DifySetups DIFY_SETUPS = DifySetups.DIFY_SETUPS;

    /**
     * The table <code>public.document_segments</code>.
     */
    public final DocumentSegments DOCUMENT_SEGMENTS = DocumentSegments.DOCUMENT_SEGMENTS;

    /**
     * The table <code>public.documents</code>.
     */
    public final Documents DOCUMENTS = Documents.DOCUMENTS;

    /**
     * The table <code>public.embeddings</code>.
     */
    public final Embeddings EMBEDDINGS = Embeddings.EMBEDDINGS;

    /**
     * The table <code>public.end_users</code>.
     */
    public final EndUsers END_USERS = EndUsers.END_USERS;

    /**
     * The table <code>public.installed_apps</code>.
     */
    public final InstalledApps INSTALLED_APPS = InstalledApps.INSTALLED_APPS;

    /**
     * The table <code>public.invitation_codes</code>.
     */
    public final InvitationCodes INVITATION_CODES = InvitationCodes.INVITATION_CODES;

    /**
     * The table <code>public.message_agent_thoughts</code>.
     */
    public final MessageAgentThoughts MESSAGE_AGENT_THOUGHTS = MessageAgentThoughts.MESSAGE_AGENT_THOUGHTS;

    /**
     * The table <code>public.message_annotations</code>.
     */
    public final MessageAnnotations MESSAGE_ANNOTATIONS = MessageAnnotations.MESSAGE_ANNOTATIONS;

    /**
     * The table <code>public.message_chains</code>.
     */
    public final MessageChains MESSAGE_CHAINS = MessageChains.MESSAGE_CHAINS;

    /**
     * The table <code>public.message_feedbacks</code>.
     */
    public final MessageFeedbacks MESSAGE_FEEDBACKS = MessageFeedbacks.MESSAGE_FEEDBACKS;

    /**
     * The table <code>public.message_files</code>.
     */
    public final MessageFiles MESSAGE_FILES = MessageFiles.MESSAGE_FILES;

    /**
     * The table <code>public.messages</code>.
     */
    public final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.operation_logs</code>.
     */
    public final OperationLogs OPERATION_LOGS = OperationLogs.OPERATION_LOGS;

    /**
     * The table <code>public.pinned_conversations</code>.
     */
    public final PinnedConversations PINNED_CONVERSATIONS = PinnedConversations.PINNED_CONVERSATIONS;

    /**
     * The table <code>public.provider_models</code>.
     */
    public final ProviderModels PROVIDER_MODELS = ProviderModels.PROVIDER_MODELS;

    /**
     * The table <code>public.provider_orders</code>.
     */
    public final ProviderOrders PROVIDER_ORDERS = ProviderOrders.PROVIDER_ORDERS;

    /**
     * The table <code>public.providers</code>.
     */
    public final Providers PROVIDERS = Providers.PROVIDERS;

    /**
     * The table <code>public.recommended_apps</code>.
     */
    public final RecommendedApps RECOMMENDED_APPS = RecommendedApps.RECOMMENDED_APPS;

    /**
     * The table <code>public.saved_messages</code>.
     */
    public final SavedMessages SAVED_MESSAGES = SavedMessages.SAVED_MESSAGES;

    /**
     * The table <code>public.sites</code>.
     */
    public final Sites SITES = Sites.SITES;

    /**
     * The table <code>public.tenant_account_joins</code>.
     */
    public final TenantAccountJoins TENANT_ACCOUNT_JOINS = TenantAccountJoins.TENANT_ACCOUNT_JOINS;

    /**
     * The table <code>public.tenant_default_models</code>.
     */
    public final TenantDefaultModels TENANT_DEFAULT_MODELS = TenantDefaultModels.TENANT_DEFAULT_MODELS;

    /**
     * The table <code>public.tenant_preferred_model_providers</code>.
     */
    public final TenantPreferredModelProviders TENANT_PREFERRED_MODEL_PROVIDERS = TenantPreferredModelProviders.TENANT_PREFERRED_MODEL_PROVIDERS;

    /**
     * The table <code>public.tenants</code>.
     */
    public final Tenants TENANTS = Tenants.TENANTS;

    /**
     * The table <code>public.tool_api_providers</code>.
     */
    public final ToolApiProviders TOOL_API_PROVIDERS = ToolApiProviders.TOOL_API_PROVIDERS;

    /**
     * The table <code>public.tool_builtin_providers</code>.
     */
    public final ToolBuiltinProviders TOOL_BUILTIN_PROVIDERS = ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS;

    /**
     * The table <code>public.tool_conversation_variables</code>.
     */
    public final ToolConversationVariables TOOL_CONVERSATION_VARIABLES = ToolConversationVariables.TOOL_CONVERSATION_VARIABLES;

    /**
     * The table <code>public.tool_files</code>.
     */
    public final ToolFiles TOOL_FILES = ToolFiles.TOOL_FILES;

    /**
     * The table <code>public.tool_model_invokes</code>.
     */
    public final ToolModelInvokes TOOL_MODEL_INVOKES = ToolModelInvokes.TOOL_MODEL_INVOKES;

    /**
     * The table <code>public.tool_providers</code>.
     */
    public final ToolProviders TOOL_PROVIDERS = ToolProviders.TOOL_PROVIDERS;

    /**
     * The table <code>public.tool_published_apps</code>.
     */
    public final ToolPublishedApps TOOL_PUBLISHED_APPS = ToolPublishedApps.TOOL_PUBLISHED_APPS;

    /**
     * The table <code>public.upload_files</code>.
     */
    public final UploadFiles UPLOAD_FILES = UploadFiles.UPLOAD_FILES;

    /**
     * The table <code>public.workflow_app_logs</code>.
     */
    public final WorkflowAppLogs WORKFLOW_APP_LOGS = WorkflowAppLogs.WORKFLOW_APP_LOGS;

    /**
     * The table <code>public.workflow_node_executions</code>.
     */
    public final WorkflowNodeExecutions WORKFLOW_NODE_EXECUTIONS = WorkflowNodeExecutions.WORKFLOW_NODE_EXECUTIONS;

    /**
     * The table <code>public.workflow_runs</code>.
     */
    public final WorkflowRuns WORKFLOW_RUNS = WorkflowRuns.WORKFLOW_RUNS;

    /**
     * The table <code>public.workflows</code>.
     */
    public final Workflows WORKFLOWS = Workflows.WORKFLOWS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.INVITATION_CODES_ID_SEQ,
            Sequences.TASK_ID_SEQUENCE,
            Sequences.TASKSET_ID_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AccountIntegrates.ACCOUNT_INTEGRATES,
            Accounts.ACCOUNTS,
            AlembicVersion.ALEMBIC_VERSION,
            ApiBasedExtensions.API_BASED_EXTENSIONS,
            ApiRequests.API_REQUESTS,
            ApiTokens.API_TOKENS,
            AppAnnotationHitHistories.APP_ANNOTATION_HIT_HISTORIES,
            AppAnnotationSettings.APP_ANNOTATION_SETTINGS,
            AppDatasetJoins.APP_DATASET_JOINS,
            AppModelConfigs.APP_MODEL_CONFIGS,
            Apps.APPS,
            CeleryTaskmeta.CELERY_TASKMETA,
            CeleryTasksetmeta.CELERY_TASKSETMETA,
            Conversations.CONVERSATIONS,
            DataSourceBindings.DATA_SOURCE_BINDINGS,
            DatasetCollectionBindings.DATASET_COLLECTION_BINDINGS,
            DatasetKeywordTables.DATASET_KEYWORD_TABLES,
            DatasetProcessRules.DATASET_PROCESS_RULES,
            DatasetQueries.DATASET_QUERIES,
            DatasetRetrieverResources.DATASET_RETRIEVER_RESOURCES,
            Datasets.DATASETS,
            DifySetups.DIFY_SETUPS,
            DocumentSegments.DOCUMENT_SEGMENTS,
            Documents.DOCUMENTS,
            Embeddings.EMBEDDINGS,
            EndUsers.END_USERS,
            InstalledApps.INSTALLED_APPS,
            InvitationCodes.INVITATION_CODES,
            MessageAgentThoughts.MESSAGE_AGENT_THOUGHTS,
            MessageAnnotations.MESSAGE_ANNOTATIONS,
            MessageChains.MESSAGE_CHAINS,
            MessageFeedbacks.MESSAGE_FEEDBACKS,
            MessageFiles.MESSAGE_FILES,
            Messages.MESSAGES,
            OperationLogs.OPERATION_LOGS,
            PinnedConversations.PINNED_CONVERSATIONS,
            ProviderModels.PROVIDER_MODELS,
            ProviderOrders.PROVIDER_ORDERS,
            Providers.PROVIDERS,
            RecommendedApps.RECOMMENDED_APPS,
            SavedMessages.SAVED_MESSAGES,
            Sites.SITES,
            TenantAccountJoins.TENANT_ACCOUNT_JOINS,
            TenantDefaultModels.TENANT_DEFAULT_MODELS,
            TenantPreferredModelProviders.TENANT_PREFERRED_MODEL_PROVIDERS,
            Tenants.TENANTS,
            ToolApiProviders.TOOL_API_PROVIDERS,
            ToolBuiltinProviders.TOOL_BUILTIN_PROVIDERS,
            ToolConversationVariables.TOOL_CONVERSATION_VARIABLES,
            ToolFiles.TOOL_FILES,
            ToolModelInvokes.TOOL_MODEL_INVOKES,
            ToolProviders.TOOL_PROVIDERS,
            ToolPublishedApps.TOOL_PUBLISHED_APPS,
            UploadFiles.UPLOAD_FILES,
            WorkflowAppLogs.WORKFLOW_APP_LOGS,
            WorkflowNodeExecutions.WORKFLOW_NODE_EXECUTIONS,
            WorkflowRuns.WORKFLOW_RUNS,
            Workflows.WORKFLOWS);
    }
}
