/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppModelConfigs implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          appId;
    private String        provider;
    private String        modelId;
    private JSON          configs;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String        openingStatement;
    private String        suggestedQuestions;
    private String        suggestedQuestionsAfterAnswer;
    private String        moreLikeThis;
    private String        model;
    private String        userInputForm;
    private String        prePrompt;
    private String        agentMode;
    private String        speechToText;
    private String        sensitiveWordAvoidance;
    private String        retrieverResource;
    private String        datasetQueryVariable;
    private String        promptType;
    private String        chatPromptConfig;
    private String        completionPromptConfig;
    private String        datasetConfigs;
    private String        externalDataTools;
    private String        fileUpload;
    private String        textToSpeech;

    public AppModelConfigs() {}

    public AppModelConfigs(AppModelConfigs value) {
        this.id = value.id;
        this.appId = value.appId;
        this.provider = value.provider;
        this.modelId = value.modelId;
        this.configs = value.configs;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.openingStatement = value.openingStatement;
        this.suggestedQuestions = value.suggestedQuestions;
        this.suggestedQuestionsAfterAnswer = value.suggestedQuestionsAfterAnswer;
        this.moreLikeThis = value.moreLikeThis;
        this.model = value.model;
        this.userInputForm = value.userInputForm;
        this.prePrompt = value.prePrompt;
        this.agentMode = value.agentMode;
        this.speechToText = value.speechToText;
        this.sensitiveWordAvoidance = value.sensitiveWordAvoidance;
        this.retrieverResource = value.retrieverResource;
        this.datasetQueryVariable = value.datasetQueryVariable;
        this.promptType = value.promptType;
        this.chatPromptConfig = value.chatPromptConfig;
        this.completionPromptConfig = value.completionPromptConfig;
        this.datasetConfigs = value.datasetConfigs;
        this.externalDataTools = value.externalDataTools;
        this.fileUpload = value.fileUpload;
        this.textToSpeech = value.textToSpeech;
    }

    public AppModelConfigs(
        UUID          id,
        UUID          appId,
        String        provider,
        String        modelId,
        JSON          configs,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        String        openingStatement,
        String        suggestedQuestions,
        String        suggestedQuestionsAfterAnswer,
        String        moreLikeThis,
        String        model,
        String        userInputForm,
        String        prePrompt,
        String        agentMode,
        String        speechToText,
        String        sensitiveWordAvoidance,
        String        retrieverResource,
        String        datasetQueryVariable,
        String        promptType,
        String        chatPromptConfig,
        String        completionPromptConfig,
        String        datasetConfigs,
        String        externalDataTools,
        String        fileUpload,
        String        textToSpeech
    ) {
        this.id = id;
        this.appId = appId;
        this.provider = provider;
        this.modelId = modelId;
        this.configs = configs;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.openingStatement = openingStatement;
        this.suggestedQuestions = suggestedQuestions;
        this.suggestedQuestionsAfterAnswer = suggestedQuestionsAfterAnswer;
        this.moreLikeThis = moreLikeThis;
        this.model = model;
        this.userInputForm = userInputForm;
        this.prePrompt = prePrompt;
        this.agentMode = agentMode;
        this.speechToText = speechToText;
        this.sensitiveWordAvoidance = sensitiveWordAvoidance;
        this.retrieverResource = retrieverResource;
        this.datasetQueryVariable = datasetQueryVariable;
        this.promptType = promptType;
        this.chatPromptConfig = chatPromptConfig;
        this.completionPromptConfig = completionPromptConfig;
        this.datasetConfigs = datasetConfigs;
        this.externalDataTools = externalDataTools;
        this.fileUpload = fileUpload;
        this.textToSpeech = textToSpeech;
    }

    /**
     * Getter for <code>public.app_model_configs.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.app_model_configs.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.app_model_configs.app_id</code>.
     */
    public UUID getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>public.app_model_configs.app_id</code>.
     */
    public void setAppId(UUID appId) {
        this.appId = appId;
    }

    /**
     * Getter for <code>public.app_model_configs.provider</code>.
     */
    public String getProvider() {
        return this.provider;
    }

    /**
     * Setter for <code>public.app_model_configs.provider</code>.
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * Getter for <code>public.app_model_configs.model_id</code>.
     */
    public String getModelId() {
        return this.modelId;
    }

    /**
     * Setter for <code>public.app_model_configs.model_id</code>.
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * Getter for <code>public.app_model_configs.configs</code>.
     */
    public JSON getConfigs() {
        return this.configs;
    }

    /**
     * Setter for <code>public.app_model_configs.configs</code>.
     */
    public void setConfigs(JSON configs) {
        this.configs = configs;
    }

    /**
     * Getter for <code>public.app_model_configs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.app_model_configs.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.app_model_configs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.app_model_configs.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.app_model_configs.opening_statement</code>.
     */
    public String getOpeningStatement() {
        return this.openingStatement;
    }

    /**
     * Setter for <code>public.app_model_configs.opening_statement</code>.
     */
    public void setOpeningStatement(String openingStatement) {
        this.openingStatement = openingStatement;
    }

    /**
     * Getter for <code>public.app_model_configs.suggested_questions</code>.
     */
    public String getSuggestedQuestions() {
        return this.suggestedQuestions;
    }

    /**
     * Setter for <code>public.app_model_configs.suggested_questions</code>.
     */
    public void setSuggestedQuestions(String suggestedQuestions) {
        this.suggestedQuestions = suggestedQuestions;
    }

    /**
     * Getter for <code>public.app_model_configs.suggested_questions_after_answer</code>.
     */
    public String getSuggestedQuestionsAfterAnswer() {
        return this.suggestedQuestionsAfterAnswer;
    }

    /**
     * Setter for <code>public.app_model_configs.suggested_questions_after_answer</code>.
     */
    public void setSuggestedQuestionsAfterAnswer(String suggestedQuestionsAfterAnswer) {
        this.suggestedQuestionsAfterAnswer = suggestedQuestionsAfterAnswer;
    }

    /**
     * Getter for <code>public.app_model_configs.more_like_this</code>.
     */
    public String getMoreLikeThis() {
        return this.moreLikeThis;
    }

    /**
     * Setter for <code>public.app_model_configs.more_like_this</code>.
     */
    public void setMoreLikeThis(String moreLikeThis) {
        this.moreLikeThis = moreLikeThis;
    }

    /**
     * Getter for <code>public.app_model_configs.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>public.app_model_configs.model</code>.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>public.app_model_configs.user_input_form</code>.
     */
    public String getUserInputForm() {
        return this.userInputForm;
    }

    /**
     * Setter for <code>public.app_model_configs.user_input_form</code>.
     */
    public void setUserInputForm(String userInputForm) {
        this.userInputForm = userInputForm;
    }

    /**
     * Getter for <code>public.app_model_configs.pre_prompt</code>.
     */
    public String getPrePrompt() {
        return this.prePrompt;
    }

    /**
     * Setter for <code>public.app_model_configs.pre_prompt</code>.
     */
    public void setPrePrompt(String prePrompt) {
        this.prePrompt = prePrompt;
    }

    /**
     * Getter for <code>public.app_model_configs.agent_mode</code>.
     */
    public String getAgentMode() {
        return this.agentMode;
    }

    /**
     * Setter for <code>public.app_model_configs.agent_mode</code>.
     */
    public void setAgentMode(String agentMode) {
        this.agentMode = agentMode;
    }

    /**
     * Getter for <code>public.app_model_configs.speech_to_text</code>.
     */
    public String getSpeechToText() {
        return this.speechToText;
    }

    /**
     * Setter for <code>public.app_model_configs.speech_to_text</code>.
     */
    public void setSpeechToText(String speechToText) {
        this.speechToText = speechToText;
    }

    /**
     * Getter for <code>public.app_model_configs.sensitive_word_avoidance</code>.
     */
    public String getSensitiveWordAvoidance() {
        return this.sensitiveWordAvoidance;
    }

    /**
     * Setter for <code>public.app_model_configs.sensitive_word_avoidance</code>.
     */
    public void setSensitiveWordAvoidance(String sensitiveWordAvoidance) {
        this.sensitiveWordAvoidance = sensitiveWordAvoidance;
    }

    /**
     * Getter for <code>public.app_model_configs.retriever_resource</code>.
     */
    public String getRetrieverResource() {
        return this.retrieverResource;
    }

    /**
     * Setter for <code>public.app_model_configs.retriever_resource</code>.
     */
    public void setRetrieverResource(String retrieverResource) {
        this.retrieverResource = retrieverResource;
    }

    /**
     * Getter for <code>public.app_model_configs.dataset_query_variable</code>.
     */
    public String getDatasetQueryVariable() {
        return this.datasetQueryVariable;
    }

    /**
     * Setter for <code>public.app_model_configs.dataset_query_variable</code>.
     */
    public void setDatasetQueryVariable(String datasetQueryVariable) {
        this.datasetQueryVariable = datasetQueryVariable;
    }

    /**
     * Getter for <code>public.app_model_configs.prompt_type</code>.
     */
    public String getPromptType() {
        return this.promptType;
    }

    /**
     * Setter for <code>public.app_model_configs.prompt_type</code>.
     */
    public void setPromptType(String promptType) {
        this.promptType = promptType;
    }

    /**
     * Getter for <code>public.app_model_configs.chat_prompt_config</code>.
     */
    public String getChatPromptConfig() {
        return this.chatPromptConfig;
    }

    /**
     * Setter for <code>public.app_model_configs.chat_prompt_config</code>.
     */
    public void setChatPromptConfig(String chatPromptConfig) {
        this.chatPromptConfig = chatPromptConfig;
    }

    /**
     * Getter for <code>public.app_model_configs.completion_prompt_config</code>.
     */
    public String getCompletionPromptConfig() {
        return this.completionPromptConfig;
    }

    /**
     * Setter for <code>public.app_model_configs.completion_prompt_config</code>.
     */
    public void setCompletionPromptConfig(String completionPromptConfig) {
        this.completionPromptConfig = completionPromptConfig;
    }

    /**
     * Getter for <code>public.app_model_configs.dataset_configs</code>.
     */
    public String getDatasetConfigs() {
        return this.datasetConfigs;
    }

    /**
     * Setter for <code>public.app_model_configs.dataset_configs</code>.
     */
    public void setDatasetConfigs(String datasetConfigs) {
        this.datasetConfigs = datasetConfigs;
    }

    /**
     * Getter for <code>public.app_model_configs.external_data_tools</code>.
     */
    public String getExternalDataTools() {
        return this.externalDataTools;
    }

    /**
     * Setter for <code>public.app_model_configs.external_data_tools</code>.
     */
    public void setExternalDataTools(String externalDataTools) {
        this.externalDataTools = externalDataTools;
    }

    /**
     * Getter for <code>public.app_model_configs.file_upload</code>.
     */
    public String getFileUpload() {
        return this.fileUpload;
    }

    /**
     * Setter for <code>public.app_model_configs.file_upload</code>.
     */
    public void setFileUpload(String fileUpload) {
        this.fileUpload = fileUpload;
    }

    /**
     * Getter for <code>public.app_model_configs.text_to_speech</code>.
     */
    public String getTextToSpeech() {
        return this.textToSpeech;
    }

    /**
     * Setter for <code>public.app_model_configs.text_to_speech</code>.
     */
    public void setTextToSpeech(String textToSpeech) {
        this.textToSpeech = textToSpeech;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppModelConfigs (");

        sb.append(id);
        sb.append(", ").append(appId);
        sb.append(", ").append(provider);
        sb.append(", ").append(modelId);
        sb.append(", ").append(configs);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(openingStatement);
        sb.append(", ").append(suggestedQuestions);
        sb.append(", ").append(suggestedQuestionsAfterAnswer);
        sb.append(", ").append(moreLikeThis);
        sb.append(", ").append(model);
        sb.append(", ").append(userInputForm);
        sb.append(", ").append(prePrompt);
        sb.append(", ").append(agentMode);
        sb.append(", ").append(speechToText);
        sb.append(", ").append(sensitiveWordAvoidance);
        sb.append(", ").append(retrieverResource);
        sb.append(", ").append(datasetQueryVariable);
        sb.append(", ").append(promptType);
        sb.append(", ").append(chatPromptConfig);
        sb.append(", ").append(completionPromptConfig);
        sb.append(", ").append(datasetConfigs);
        sb.append(", ").append(externalDataTools);
        sb.append(", ").append(fileUpload);
        sb.append(", ").append(textToSpeech);

        sb.append(")");
        return sb.toString();
    }
}
