/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Apps implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          tenantId;
    private String        name;
    private String        mode;
    private String        icon;
    private String        iconBackground;
    private UUID          appModelConfigId;
    private String        status;
    private Boolean       enableSite;
    private Boolean       enableApi;
    private Integer       apiRpm;
    private Integer       apiRph;
    private Boolean       isDemo;
    private Boolean       isPublic;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Boolean       isUniversal;
    private UUID          workflowId;
    private String        description;

    public Apps() {}

    public Apps(Apps value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.name = value.name;
        this.mode = value.mode;
        this.icon = value.icon;
        this.iconBackground = value.iconBackground;
        this.appModelConfigId = value.appModelConfigId;
        this.status = value.status;
        this.enableSite = value.enableSite;
        this.enableApi = value.enableApi;
        this.apiRpm = value.apiRpm;
        this.apiRph = value.apiRph;
        this.isDemo = value.isDemo;
        this.isPublic = value.isPublic;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.isUniversal = value.isUniversal;
        this.workflowId = value.workflowId;
        this.description = value.description;
    }

    public Apps(
        UUID          id,
        UUID          tenantId,
        String        name,
        String        mode,
        String        icon,
        String        iconBackground,
        UUID          appModelConfigId,
        String        status,
        Boolean       enableSite,
        Boolean       enableApi,
        Integer       apiRpm,
        Integer       apiRph,
        Boolean       isDemo,
        Boolean       isPublic,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        Boolean       isUniversal,
        UUID          workflowId,
        String        description
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.name = name;
        this.mode = mode;
        this.icon = icon;
        this.iconBackground = iconBackground;
        this.appModelConfigId = appModelConfigId;
        this.status = status;
        this.enableSite = enableSite;
        this.enableApi = enableApi;
        this.apiRpm = apiRpm;
        this.apiRph = apiRph;
        this.isDemo = isDemo;
        this.isPublic = isPublic;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.isUniversal = isUniversal;
        this.workflowId = workflowId;
        this.description = description;
    }

    /**
     * Getter for <code>public.apps.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.apps.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.apps.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.apps.tenant_id</code>.
     */
    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>public.apps.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.apps.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.apps.mode</code>.
     */
    public String getMode() {
        return this.mode;
    }

    /**
     * Setter for <code>public.apps.mode</code>.
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    /**
     * Getter for <code>public.apps.icon</code>.
     */
    public String getIcon() {
        return this.icon;
    }

    /**
     * Setter for <code>public.apps.icon</code>.
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Getter for <code>public.apps.icon_background</code>.
     */
    public String getIconBackground() {
        return this.iconBackground;
    }

    /**
     * Setter for <code>public.apps.icon_background</code>.
     */
    public void setIconBackground(String iconBackground) {
        this.iconBackground = iconBackground;
    }

    /**
     * Getter for <code>public.apps.app_model_config_id</code>.
     */
    public UUID getAppModelConfigId() {
        return this.appModelConfigId;
    }

    /**
     * Setter for <code>public.apps.app_model_config_id</code>.
     */
    public void setAppModelConfigId(UUID appModelConfigId) {
        this.appModelConfigId = appModelConfigId;
    }

    /**
     * Getter for <code>public.apps.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.apps.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.apps.enable_site</code>.
     */
    public Boolean getEnableSite() {
        return this.enableSite;
    }

    /**
     * Setter for <code>public.apps.enable_site</code>.
     */
    public void setEnableSite(Boolean enableSite) {
        this.enableSite = enableSite;
    }

    /**
     * Getter for <code>public.apps.enable_api</code>.
     */
    public Boolean getEnableApi() {
        return this.enableApi;
    }

    /**
     * Setter for <code>public.apps.enable_api</code>.
     */
    public void setEnableApi(Boolean enableApi) {
        this.enableApi = enableApi;
    }

    /**
     * Getter for <code>public.apps.api_rpm</code>.
     */
    public Integer getApiRpm() {
        return this.apiRpm;
    }

    /**
     * Setter for <code>public.apps.api_rpm</code>.
     */
    public void setApiRpm(Integer apiRpm) {
        this.apiRpm = apiRpm;
    }

    /**
     * Getter for <code>public.apps.api_rph</code>.
     */
    public Integer getApiRph() {
        return this.apiRph;
    }

    /**
     * Setter for <code>public.apps.api_rph</code>.
     */
    public void setApiRph(Integer apiRph) {
        this.apiRph = apiRph;
    }

    /**
     * Getter for <code>public.apps.is_demo</code>.
     */
    public Boolean getIsDemo() {
        return this.isDemo;
    }

    /**
     * Setter for <code>public.apps.is_demo</code>.
     */
    public void setIsDemo(Boolean isDemo) {
        this.isDemo = isDemo;
    }

    /**
     * Getter for <code>public.apps.is_public</code>.
     */
    public Boolean getIsPublic() {
        return this.isPublic;
    }

    /**
     * Setter for <code>public.apps.is_public</code>.
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * Getter for <code>public.apps.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.apps.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.apps.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.apps.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.apps.is_universal</code>.
     */
    public Boolean getIsUniversal() {
        return this.isUniversal;
    }

    /**
     * Setter for <code>public.apps.is_universal</code>.
     */
    public void setIsUniversal(Boolean isUniversal) {
        this.isUniversal = isUniversal;
    }

    /**
     * Getter for <code>public.apps.workflow_id</code>.
     */
    public UUID getWorkflowId() {
        return this.workflowId;
    }

    /**
     * Setter for <code>public.apps.workflow_id</code>.
     */
    public void setWorkflowId(UUID workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Getter for <code>public.apps.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.apps.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Apps (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(name);
        sb.append(", ").append(mode);
        sb.append(", ").append(icon);
        sb.append(", ").append(iconBackground);
        sb.append(", ").append(appModelConfigId);
        sb.append(", ").append(status);
        sb.append(", ").append(enableSite);
        sb.append(", ").append(enableApi);
        sb.append(", ").append(apiRpm);
        sb.append(", ").append(apiRph);
        sb.append(", ").append(isDemo);
        sb.append(", ").append(isPublic);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(isUniversal);
        sb.append(", ").append(workflowId);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
