/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetKeywordTables implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   datasetId;
    private String keywordTable;

    public DatasetKeywordTables() {}

    public DatasetKeywordTables(DatasetKeywordTables value) {
        this.id = value.id;
        this.datasetId = value.datasetId;
        this.keywordTable = value.keywordTable;
    }

    public DatasetKeywordTables(
        UUID   id,
        UUID   datasetId,
        String keywordTable
    ) {
        this.id = id;
        this.datasetId = datasetId;
        this.keywordTable = keywordTable;
    }

    /**
     * Getter for <code>public.dataset_keyword_tables.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.dataset_keyword_tables.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.dataset_keyword_tables.dataset_id</code>.
     */
    public UUID getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>public.dataset_keyword_tables.dataset_id</code>.
     */
    public void setDatasetId(UUID datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>public.dataset_keyword_tables.keyword_table</code>.
     */
    public String getKeywordTable() {
        return this.keywordTable;
    }

    /**
     * Setter for <code>public.dataset_keyword_tables.keyword_table</code>.
     */
    public void setKeywordTable(String keywordTable) {
        this.keywordTable = keywordTable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatasetKeywordTables (");

        sb.append(id);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(keywordTable);

        sb.append(")");
        return sb.toString();
    }
}
