/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSourceBindings implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          tenantId;
    private String        accessToken;
    private String        provider;
    private JSONB         sourceInfo;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Boolean       disabled;

    public DataSourceBindings() {}

    public DataSourceBindings(DataSourceBindings value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.accessToken = value.accessToken;
        this.provider = value.provider;
        this.sourceInfo = value.sourceInfo;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.disabled = value.disabled;
    }

    public DataSourceBindings(
        UUID          id,
        UUID          tenantId,
        String        accessToken,
        String        provider,
        JSONB         sourceInfo,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        Boolean       disabled
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.accessToken = accessToken;
        this.provider = provider;
        this.sourceInfo = sourceInfo;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.disabled = disabled;
    }

    /**
     * Getter for <code>public.data_source_bindings.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.data_source_bindings.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.data_source_bindings.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.data_source_bindings.tenant_id</code>.
     */
    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>public.data_source_bindings.access_token</code>.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>public.data_source_bindings.access_token</code>.
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Getter for <code>public.data_source_bindings.provider</code>.
     */
    public String getProvider() {
        return this.provider;
    }

    /**
     * Setter for <code>public.data_source_bindings.provider</code>.
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * Getter for <code>public.data_source_bindings.source_info</code>.
     */
    public JSONB getSourceInfo() {
        return this.sourceInfo;
    }

    /**
     * Setter for <code>public.data_source_bindings.source_info</code>.
     */
    public void setSourceInfo(JSONB sourceInfo) {
        this.sourceInfo = sourceInfo;
    }

    /**
     * Getter for <code>public.data_source_bindings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.data_source_bindings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.data_source_bindings.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.data_source_bindings.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.data_source_bindings.disabled</code>.
     */
    public Boolean getDisabled() {
        return this.disabled;
    }

    /**
     * Setter for <code>public.data_source_bindings.disabled</code>.
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataSourceBindings (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(provider);
        sb.append(", ").append(sourceInfo);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(disabled);

        sb.append(")");
        return sb.toString();
    }
}
