/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DifySetups implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        version;
    private LocalDateTime setupAt;

    public DifySetups() {}

    public DifySetups(DifySetups value) {
        this.version = value.version;
        this.setupAt = value.setupAt;
    }

    public DifySetups(
        String        version,
        LocalDateTime setupAt
    ) {
        this.version = version;
        this.setupAt = setupAt;
    }

    /**
     * Getter for <code>public.dify_setups.version</code>.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.dify_setups.version</code>.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for <code>public.dify_setups.setup_at</code>.
     */
    public LocalDateTime getSetupAt() {
        return this.setupAt;
    }

    /**
     * Setter for <code>public.dify_setups.setup_at</code>.
     */
    public void setSetupAt(LocalDateTime setupAt) {
        this.setupAt = setupAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DifySetups (");

        sb.append(version);
        sb.append(", ").append(setupAt);

        sb.append(")");
        return sb.toString();
    }
}
