/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentSegments implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          tenantId;
    private UUID          datasetId;
    private UUID          documentId;
    private Integer       position;
    private String        content;
    private Integer       wordCount;
    private Integer       tokens;
    private JSON          keywords;
    private String        indexNodeId;
    private String        indexNodeHash;
    private Integer       hitCount;
    private Boolean       enabled;
    private LocalDateTime disabledAt;
    private UUID          disabledBy;
    private String        status;
    private UUID          createdBy;
    private LocalDateTime createdAt;
    private LocalDateTime indexingAt;
    private LocalDateTime completedAt;
    private String        error;
    private LocalDateTime stoppedAt;
    private String        answer;
    private UUID          updatedBy;
    private LocalDateTime updatedAt;

    public DocumentSegments() {}

    public DocumentSegments(DocumentSegments value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.datasetId = value.datasetId;
        this.documentId = value.documentId;
        this.position = value.position;
        this.content = value.content;
        this.wordCount = value.wordCount;
        this.tokens = value.tokens;
        this.keywords = value.keywords;
        this.indexNodeId = value.indexNodeId;
        this.indexNodeHash = value.indexNodeHash;
        this.hitCount = value.hitCount;
        this.enabled = value.enabled;
        this.disabledAt = value.disabledAt;
        this.disabledBy = value.disabledBy;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.indexingAt = value.indexingAt;
        this.completedAt = value.completedAt;
        this.error = value.error;
        this.stoppedAt = value.stoppedAt;
        this.answer = value.answer;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
    }

    public DocumentSegments(
        UUID          id,
        UUID          tenantId,
        UUID          datasetId,
        UUID          documentId,
        Integer       position,
        String        content,
        Integer       wordCount,
        Integer       tokens,
        JSON          keywords,
        String        indexNodeId,
        String        indexNodeHash,
        Integer       hitCount,
        Boolean       enabled,
        LocalDateTime disabledAt,
        UUID          disabledBy,
        String        status,
        UUID          createdBy,
        LocalDateTime createdAt,
        LocalDateTime indexingAt,
        LocalDateTime completedAt,
        String        error,
        LocalDateTime stoppedAt,
        String        answer,
        UUID          updatedBy,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.datasetId = datasetId;
        this.documentId = documentId;
        this.position = position;
        this.content = content;
        this.wordCount = wordCount;
        this.tokens = tokens;
        this.keywords = keywords;
        this.indexNodeId = indexNodeId;
        this.indexNodeHash = indexNodeHash;
        this.hitCount = hitCount;
        this.enabled = enabled;
        this.disabledAt = disabledAt;
        this.disabledBy = disabledBy;
        this.status = status;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.indexingAt = indexingAt;
        this.completedAt = completedAt;
        this.error = error;
        this.stoppedAt = stoppedAt;
        this.answer = answer;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.document_segments.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.document_segments.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.document_segments.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.document_segments.tenant_id</code>.
     */
    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>public.document_segments.dataset_id</code>.
     */
    public UUID getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>public.document_segments.dataset_id</code>.
     */
    public void setDatasetId(UUID datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>public.document_segments.document_id</code>.
     */
    public UUID getDocumentId() {
        return this.documentId;
    }

    /**
     * Setter for <code>public.document_segments.document_id</code>.
     */
    public void setDocumentId(UUID documentId) {
        this.documentId = documentId;
    }

    /**
     * Getter for <code>public.document_segments.position</code>.
     */
    public Integer getPosition() {
        return this.position;
    }

    /**
     * Setter for <code>public.document_segments.position</code>.
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * Getter for <code>public.document_segments.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.document_segments.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>public.document_segments.word_count</code>.
     */
    public Integer getWordCount() {
        return this.wordCount;
    }

    /**
     * Setter for <code>public.document_segments.word_count</code>.
     */
    public void setWordCount(Integer wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * Getter for <code>public.document_segments.tokens</code>.
     */
    public Integer getTokens() {
        return this.tokens;
    }

    /**
     * Setter for <code>public.document_segments.tokens</code>.
     */
    public void setTokens(Integer tokens) {
        this.tokens = tokens;
    }

    /**
     * Getter for <code>public.document_segments.keywords</code>.
     */
    public JSON getKeywords() {
        return this.keywords;
    }

    /**
     * Setter for <code>public.document_segments.keywords</code>.
     */
    public void setKeywords(JSON keywords) {
        this.keywords = keywords;
    }

    /**
     * Getter for <code>public.document_segments.index_node_id</code>.
     */
    public String getIndexNodeId() {
        return this.indexNodeId;
    }

    /**
     * Setter for <code>public.document_segments.index_node_id</code>.
     */
    public void setIndexNodeId(String indexNodeId) {
        this.indexNodeId = indexNodeId;
    }

    /**
     * Getter for <code>public.document_segments.index_node_hash</code>.
     */
    public String getIndexNodeHash() {
        return this.indexNodeHash;
    }

    /**
     * Setter for <code>public.document_segments.index_node_hash</code>.
     */
    public void setIndexNodeHash(String indexNodeHash) {
        this.indexNodeHash = indexNodeHash;
    }

    /**
     * Getter for <code>public.document_segments.hit_count</code>.
     */
    public Integer getHitCount() {
        return this.hitCount;
    }

    /**
     * Setter for <code>public.document_segments.hit_count</code>.
     */
    public void setHitCount(Integer hitCount) {
        this.hitCount = hitCount;
    }

    /**
     * Getter for <code>public.document_segments.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>public.document_segments.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>public.document_segments.disabled_at</code>.
     */
    public LocalDateTime getDisabledAt() {
        return this.disabledAt;
    }

    /**
     * Setter for <code>public.document_segments.disabled_at</code>.
     */
    public void setDisabledAt(LocalDateTime disabledAt) {
        this.disabledAt = disabledAt;
    }

    /**
     * Getter for <code>public.document_segments.disabled_by</code>.
     */
    public UUID getDisabledBy() {
        return this.disabledBy;
    }

    /**
     * Setter for <code>public.document_segments.disabled_by</code>.
     */
    public void setDisabledBy(UUID disabledBy) {
        this.disabledBy = disabledBy;
    }

    /**
     * Getter for <code>public.document_segments.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.document_segments.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.document_segments.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.document_segments.created_by</code>.
     */
    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.document_segments.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.document_segments.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.document_segments.indexing_at</code>.
     */
    public LocalDateTime getIndexingAt() {
        return this.indexingAt;
    }

    /**
     * Setter for <code>public.document_segments.indexing_at</code>.
     */
    public void setIndexingAt(LocalDateTime indexingAt) {
        this.indexingAt = indexingAt;
    }

    /**
     * Getter for <code>public.document_segments.completed_at</code>.
     */
    public LocalDateTime getCompletedAt() {
        return this.completedAt;
    }

    /**
     * Setter for <code>public.document_segments.completed_at</code>.
     */
    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for <code>public.document_segments.error</code>.
     */
    public String getError() {
        return this.error;
    }

    /**
     * Setter for <code>public.document_segments.error</code>.
     */
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for <code>public.document_segments.stopped_at</code>.
     */
    public LocalDateTime getStoppedAt() {
        return this.stoppedAt;
    }

    /**
     * Setter for <code>public.document_segments.stopped_at</code>.
     */
    public void setStoppedAt(LocalDateTime stoppedAt) {
        this.stoppedAt = stoppedAt;
    }

    /**
     * Getter for <code>public.document_segments.answer</code>.
     */
    public String getAnswer() {
        return this.answer;
    }

    /**
     * Setter for <code>public.document_segments.answer</code>.
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * Getter for <code>public.document_segments.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>public.document_segments.updated_by</code>.
     */
    public void setUpdatedBy(UUID updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for <code>public.document_segments.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.document_segments.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentSegments (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(documentId);
        sb.append(", ").append(position);
        sb.append(", ").append(content);
        sb.append(", ").append(wordCount);
        sb.append(", ").append(tokens);
        sb.append(", ").append(keywords);
        sb.append(", ").append(indexNodeId);
        sb.append(", ").append(indexNodeHash);
        sb.append(", ").append(hitCount);
        sb.append(", ").append(enabled);
        sb.append(", ").append(disabledAt);
        sb.append(", ").append(disabledBy);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(indexingAt);
        sb.append(", ").append(completedAt);
        sb.append(", ").append(error);
        sb.append(", ").append(stoppedAt);
        sb.append(", ").append(answer);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
