/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Embeddings implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private String        hash;
    private byte[]        embedding;
    private LocalDateTime createdAt;
    private String        modelName;

    public Embeddings() {}

    public Embeddings(Embeddings value) {
        this.id = value.id;
        this.hash = value.hash;
        this.embedding = value.embedding;
        this.createdAt = value.createdAt;
        this.modelName = value.modelName;
    }

    public Embeddings(
        UUID          id,
        String        hash,
        byte[]        embedding,
        LocalDateTime createdAt,
        String        modelName
    ) {
        this.id = id;
        this.hash = hash;
        this.embedding = embedding;
        this.createdAt = createdAt;
        this.modelName = modelName;
    }

    /**
     * Getter for <code>public.embeddings.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.embeddings.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.embeddings.hash</code>.
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>public.embeddings.hash</code>.
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>public.embeddings.embedding</code>.
     */
    public byte[] getEmbedding() {
        return this.embedding;
    }

    /**
     * Setter for <code>public.embeddings.embedding</code>.
     */
    public void setEmbedding(byte[] embedding) {
        this.embedding = embedding;
    }

    /**
     * Getter for <code>public.embeddings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.embeddings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.embeddings.model_name</code>.
     */
    public String getModelName() {
        return this.modelName;
    }

    /**
     * Setter for <code>public.embeddings.model_name</code>.
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Embeddings (");

        sb.append(id);
        sb.append(", ").append(hash);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modelName);

        sb.append(")");
        return sb.toString();
    }
}
