/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstalledApps implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          tenantId;
    private UUID          appId;
    private UUID          appOwnerTenantId;
    private Integer       position;
    private Boolean       isPinned;
    private LocalDateTime lastUsedAt;
    private LocalDateTime createdAt;

    public InstalledApps() {}

    public InstalledApps(InstalledApps value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.appId = value.appId;
        this.appOwnerTenantId = value.appOwnerTenantId;
        this.position = value.position;
        this.isPinned = value.isPinned;
        this.lastUsedAt = value.lastUsedAt;
        this.createdAt = value.createdAt;
    }

    public InstalledApps(
        UUID          id,
        UUID          tenantId,
        UUID          appId,
        UUID          appOwnerTenantId,
        Integer       position,
        Boolean       isPinned,
        LocalDateTime lastUsedAt,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.appId = appId;
        this.appOwnerTenantId = appOwnerTenantId;
        this.position = position;
        this.isPinned = isPinned;
        this.lastUsedAt = lastUsedAt;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.installed_apps.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.installed_apps.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.installed_apps.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.installed_apps.tenant_id</code>.
     */
    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>public.installed_apps.app_id</code>.
     */
    public UUID getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>public.installed_apps.app_id</code>.
     */
    public void setAppId(UUID appId) {
        this.appId = appId;
    }

    /**
     * Getter for <code>public.installed_apps.app_owner_tenant_id</code>.
     */
    public UUID getAppOwnerTenantId() {
        return this.appOwnerTenantId;
    }

    /**
     * Setter for <code>public.installed_apps.app_owner_tenant_id</code>.
     */
    public void setAppOwnerTenantId(UUID appOwnerTenantId) {
        this.appOwnerTenantId = appOwnerTenantId;
    }

    /**
     * Getter for <code>public.installed_apps.position</code>.
     */
    public Integer getPosition() {
        return this.position;
    }

    /**
     * Setter for <code>public.installed_apps.position</code>.
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * Getter for <code>public.installed_apps.is_pinned</code>.
     */
    public Boolean getIsPinned() {
        return this.isPinned;
    }

    /**
     * Setter for <code>public.installed_apps.is_pinned</code>.
     */
    public void setIsPinned(Boolean isPinned) {
        this.isPinned = isPinned;
    }

    /**
     * Getter for <code>public.installed_apps.last_used_at</code>.
     */
    public LocalDateTime getLastUsedAt() {
        return this.lastUsedAt;
    }

    /**
     * Setter for <code>public.installed_apps.last_used_at</code>.
     */
    public void setLastUsedAt(LocalDateTime lastUsedAt) {
        this.lastUsedAt = lastUsedAt;
    }

    /**
     * Getter for <code>public.installed_apps.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.installed_apps.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InstalledApps (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(appId);
        sb.append(", ").append(appOwnerTenantId);
        sb.append(", ").append(position);
        sb.append(", ").append(isPinned);
        sb.append(", ").append(lastUsedAt);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
