/*
 * This file is generated by jOOQ.
 */
package com.bonc.lops.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ToolFiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private UUID   userId;
    private UUID   tenantId;
    private UUID   conversationId;
    private String fileKey;
    private String mimetype;
    private String originalUrl;

    public ToolFiles() {}

    public ToolFiles(ToolFiles value) {
        this.id = value.id;
        this.userId = value.userId;
        this.tenantId = value.tenantId;
        this.conversationId = value.conversationId;
        this.fileKey = value.fileKey;
        this.mimetype = value.mimetype;
        this.originalUrl = value.originalUrl;
    }

    public ToolFiles(
        UUID   id,
        UUID   userId,
        UUID   tenantId,
        UUID   conversationId,
        String fileKey,
        String mimetype,
        String originalUrl
    ) {
        this.id = id;
        this.userId = userId;
        this.tenantId = tenantId;
        this.conversationId = conversationId;
        this.fileKey = fileKey;
        this.mimetype = mimetype;
        this.originalUrl = originalUrl;
    }

    /**
     * Getter for <code>public.tool_files.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tool_files.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tool_files.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.tool_files.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.tool_files.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.tool_files.tenant_id</code>.
     */
    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>public.tool_files.conversation_id</code>.
     */
    public UUID getConversationId() {
        return this.conversationId;
    }

    /**
     * Setter for <code>public.tool_files.conversation_id</code>.
     */
    public void setConversationId(UUID conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * Getter for <code>public.tool_files.file_key</code>.
     */
    public String getFileKey() {
        return this.fileKey;
    }

    /**
     * Setter for <code>public.tool_files.file_key</code>.
     */
    public void setFileKey(String fileKey) {
        this.fileKey = fileKey;
    }

    /**
     * Getter for <code>public.tool_files.mimetype</code>.
     */
    public String getMimetype() {
        return this.mimetype;
    }

    /**
     * Setter for <code>public.tool_files.mimetype</code>.
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    /**
     * Getter for <code>public.tool_files.original_url</code>.
     */
    public String getOriginalUrl() {
        return this.originalUrl;
    }

    /**
     * Setter for <code>public.tool_files.original_url</code>.
     */
    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ToolFiles (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(conversationId);
        sb.append(", ").append(fileKey);
        sb.append(", ").append(mimetype);
        sb.append(", ").append(originalUrl);

        sb.append(")");
        return sb.toString();
    }
}
