name: Run Pytest

on:
  pull_request:
    branches:
      - main
      - deploy/dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MOCK_SWITCH: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ./api/requirements.txt

      - name: Install dependencies
        run: pip install -r ./api/requirements.txt

      - name: Run pytest
        run: pytest api/tests/integration_tests/workflow